/* Generated by Claude Code 2.1.263 (claude-opus-5[1m]) */

/*
 * Unit tests for share/hmd_math.c
 */

#include <math.h>

#include "test.h"
#include "hmd_math.h"

#define EPS 1e-5f

/* The build is strict ANSI, where math.h need not define PI. */
#define PI  3.14159265358979323846

/* Transform a point by a column-major matrix. */

static void xform(float *o, const float *M, const float *v)
{
    int i;

    for (i = 0; i < 4; i++)
        o[i] = M[i]      * v[0] + M[4 + i]  * v[1] +
               M[8 + i]  * v[2] + M[12 + i] * v[3];
}

static void near_eq(float a, float b)
{
    if (fabsf(a - b) > EPS)
        exit(1);
}

/*---------------------------------------------------------------------------*/

static void test_hmd_view_identity(void)
{
    static const float q[4] = { 0.0f, 0.0f, 0.0f, 1.0f };
    static const float p[3] = { 0.0f, 0.0f, 0.0f };

    float M[16];
    int i;

    hmd_view(M, q, p);

    for (i = 0; i < 16; i++)
        near_eq(M[i], (i % 5) == 0 ? 1.0f : 0.0f);
}

/*
 * With the head moved but not turned, the world must shift by the opposite
 * amount: a point at the head's own position lands on the eye.
 */

static void test_hmd_view_translation(void)
{
    static const float q[4] = { 0.0f, 0.0f, 0.0f, 1.0f };
    static const float p[3] = { 1.0f, 2.0f, 3.0f };
    static const float v[4] = { 1.0f, 2.0f, 3.0f, 1.0f };

    float M[16], o[4];

    hmd_view(M, q, p);
    xform(o, M, v);

    near_eq(o[0], 0.0f);
    near_eq(o[1], 0.0f);
    near_eq(o[2], 0.0f);
}

/*
 * A quarter turn to the left about +Y. What was ahead of the head (-Z in the
 * reference space) must end up ahead of the eye (-Z in view space) too, and
 * what was to the head's right must land on +X. Getting the transpose the
 * wrong way round mirrors this and is invisible without stereo.
 */

static void test_hmd_view_yaw(void)
{
    const float s = (float) sin(PI / 4.0);
    const float c = (float) cos(PI / 4.0);

    const float q[4] = { 0.0f, s, 0.0f, c };
    const float p[3] = { 0.0f, 0.0f, 0.0f };

    /* Turned 90 degrees left, the head looks down -X. */

    const float ahead[4] = { -1.0f, 0.0f,  0.0f, 1.0f };
    const float right[4] = {  0.0f, 0.0f, -1.0f, 1.0f };

    float M[16], o[4];

    hmd_view(M, q, p);

    xform(o, M, ahead);
    near_eq(o[0],  0.0f);
    near_eq(o[1],  0.0f);
    near_eq(o[2], -1.0f);

    xform(o, M, right);
    near_eq(o[0], 1.0f);
    near_eq(o[1], 0.0f);
    near_eq(o[2], 0.0f);
}

/* Rotating about the head's own position must leave that position fixed. */

static void test_hmd_view_rotation_about_position(void)
{
    const float s = (float) sin(PI / 6.0);
    const float c = (float) cos(PI / 6.0);

    const float q[4] = { 0.0f, s, 0.0f, c };
    const float p[3] = { 4.0f, 1.5f, -2.0f };
    const float v[4] = { 4.0f, 1.5f, -2.0f, 1.0f };

    float M[16], o[4];

    hmd_view(M, q, p);
    xform(o, M, v);

    near_eq(o[0], 0.0f);
    near_eq(o[1], 0.0f);
    near_eq(o[2], 0.0f);
}

/*---------------------------------------------------------------------------*/

/* The near and far plane centres must land on the ends of the depth range. */

static void test_hmd_frustum_depth_range(void)
{
    static const float t[4] = { -1.0f, 1.0f, -1.0f, 1.0f };

    const float n = 0.1f;
    const float f = 100.0f;

    float M[16], o[4];

    float near_pt[4] = { 0.0f, 0.0f, 0.0f, 1.0f };
    float far_pt[4]  = { 0.0f, 0.0f, 0.0f, 1.0f };

    near_pt[2] = -n;
    far_pt[2]  = -f;

    hmd_frustum(M, t, n, f);

    xform(o, M, near_pt);
    near_eq(o[3], n);
    near_eq(o[2] / o[3], -1.0f);

    xform(o, M, far_pt);
    near_eq(o[3], f);
    near_eq(o[2] / o[3], 1.0f);
}

/* A symmetric frustum must put the frustum corners on the viewport edges. */

static void test_hmd_frustum_symmetric_edges(void)
{
    static const float t[4] = { -0.5f, 0.5f, -0.25f, 0.25f };

    float M[16], o[4];

    /* On the near plane, x = tangent * distance is the frustum's edge. */

    float edge[4] = { 0.5f * 2.0f, 0.25f * 2.0f, -2.0f, 1.0f };

    hmd_frustum(M, t, 0.1f, 100.0f);
    xform(o, M, edge);

    near_eq(o[0] / o[3], 1.0f);
    near_eq(o[1] / o[3], 1.0f);
}

/*
 * The asymmetric case is the whole reason this exists: each eye of a headset
 * sees more toward the nose than away from it, and the view axis is not the
 * centre of the image. A ray straight down -Z must land off centre.
 */

static void test_hmd_frustum_asymmetric_centre(void)
{
    static const float t[4] = { -1.0f, 0.5f, -0.75f, 0.75f };

    float M[16], o[4];

    float ahead[4]  = { 0.0f, 0.0f, -1.0f, 1.0f };
    float centre[4] = { 0.0f, 0.0f, -1.0f, 1.0f };

    hmd_frustum(M, t, 0.1f, 100.0f);

    /* Straight ahead is right of centre, because the frustum reaches
     * further to the left than to the right. */

    xform(o, M, ahead);
    if (!(o[0] / o[3] > EPS))
        exit(1);

    /* The bisector of the two horizontal tangents is what lands dead centre. */

    centre[0] = 0.5f * (-1.0f + 0.5f);
    xform(o, M, centre);
    near_eq(o[0] / o[3], 0.0f);
}

/*---------------------------------------------------------------------------*/

int test_hmd_math_all(void)
{
    int pass = 1;

    RUN_TEST("test_hmd_view_identity", test_hmd_view_identity, pass);
    RUN_TEST("test_hmd_view_translation", test_hmd_view_translation, pass);
    RUN_TEST("test_hmd_view_yaw", test_hmd_view_yaw, pass);
    RUN_TEST("test_hmd_view_rotation_about_position",
             test_hmd_view_rotation_about_position, pass);
    RUN_TEST("test_hmd_frustum_depth_range", test_hmd_frustum_depth_range,
             pass);
    RUN_TEST("test_hmd_frustum_symmetric_edges",
             test_hmd_frustum_symmetric_edges, pass);
    RUN_TEST("test_hmd_frustum_asymmetric_centre",
             test_hmd_frustum_asymmetric_centre, pass);

    return pass;
}
