/* Generated by Claude Code 2.1.263 (claude-opus-5[1m]) */

/*
 * Unit tests for the pointer ray mapping of share/vr.c
 */

#include "test.h"
#include "vr.h"

#define W 1000
#define H  500

/* The panel is VR_PANEL_SPAN metres tall over H pixels. */

#define SCALE (VR_PANEL_SPAN / (float) H)

static void expect(int got, int want)
{
    if (got != want)
        exit(1);
}

/*---------------------------------------------------------------------------*/

/* Pointing straight at the middle of the panel lands in the middle of it. */

static void test_vr_pointer_centre(void)
{
    const float o[3] = { 0.0f, VR_PANEL_HEIGHT, 0.0f };
    const float d[3] = { 0.0f, 0.0f, -1.0f };

    int x = -1, y = -1;

    if (!vr_panel_hit(o, d, W, H, &x, &y))
        exit(1);

    expect(x, W / 2);
    expect(y, H / 2);
}

/* A ray pointing away from the panel never reaches it. */

static void test_vr_pointer_behind(void)
{
    const float o[3] = { 0.0f, VR_PANEL_HEIGHT, 0.0f };
    const float d[3] = { 0.0f, 0.0f, +1.0f };

    int x = 0, y = 0;

    if (vr_panel_hit(o, d, W, H, &x, &y))
        exit(1);
}

/* Nor does one running along it. */

static void test_vr_pointer_parallel(void)
{
    const float o[3] = { 0.0f, VR_PANEL_HEIGHT, 0.0f };
    const float d[3] = { 1.0f, 0.0f, 0.0f };

    int x = 0, y = 0;

    if (vr_panel_hit(o, d, W, H, &x, &y))
        exit(1);
}

/* Standing past the panel and looking further away is still a miss. */

static void test_vr_pointer_past_the_panel(void)
{
    const float o[3] = { 0.0f, VR_PANEL_HEIGHT, -VR_PANEL_DIST - 1.0f };
    const float d[3] = { 0.0f, 0.0f, -1.0f };

    int x = 0, y = 0;

    if (vr_panel_hit(o, d, W, H, &x, &y))
        exit(1);
}

/*
 * The interface has its origin at the bottom left, so aiming higher must
 * give a larger y. Getting this upside down is the classic way to make a
 * menu that looks fine and cannot be clicked.
 */

static void test_vr_pointer_is_y_up(void)
{
    const float o[3] = { 0.0f, VR_PANEL_HEIGHT, 0.0f };

    float d[3] = { 0.0f, 0.0f, -1.0f };
    int lo_y, hi_y, x;

    d[1] = -0.2f;
    if (!vr_panel_hit(o, d, W, H, &x, &lo_y))
        exit(1);

    d[1] = +0.2f;
    if (!vr_panel_hit(o, d, W, H, &x, &hi_y))
        exit(1);

    if (!(hi_y > H / 2 && lo_y < H / 2))
        exit(1);
}

/* A known offset must land on a known pixel, at the panel's own scale. */

static void test_vr_pointer_scale(void)
{
    const float o[3] = { 0.0f, VR_PANEL_HEIGHT, 0.0f };

    /* Aim so the ray crosses the plane a quarter of a metre to the right. */

    float d[3];
    int x = 0, y = 0;

    d[0] = 0.25f;
    d[1] = 0.0f;
    d[2] = -VR_PANEL_DIST;

    if (!vr_panel_hit(o, d, W, H, &x, &y))
        exit(1);

    expect(x, (int) (0.25f / SCALE + 0.5f * (float) W));
    expect(y, H / 2);
}

/* Pointing off the edge still reports where, so the caller can decide. */

static void test_vr_pointer_off_the_edge(void)
{
    const float o[3] = { 0.0f, VR_PANEL_HEIGHT, 0.0f };

    float d[3];
    int x = 0, y = 0;

    d[0] = -4.0f;
    d[1] = 0.0f;
    d[2] = -VR_PANEL_DIST;

    if (!vr_panel_hit(o, d, W, H, &x, &y))
        exit(1);

    if (x >= 0)
        exit(1);
}

/*---------------------------------------------------------------------------*/

int test_vr_pointer_all(void)
{
    int pass = 1;

    RUN_TEST("test_vr_pointer_centre", test_vr_pointer_centre, pass);
    RUN_TEST("test_vr_pointer_behind", test_vr_pointer_behind, pass);
    RUN_TEST("test_vr_pointer_parallel", test_vr_pointer_parallel, pass);
    RUN_TEST("test_vr_pointer_past_the_panel",
             test_vr_pointer_past_the_panel, pass);
    RUN_TEST("test_vr_pointer_is_y_up", test_vr_pointer_is_y_up, pass);
    RUN_TEST("test_vr_pointer_scale", test_vr_pointer_scale, pass);
    RUN_TEST("test_vr_pointer_off_the_edge",
             test_vr_pointer_off_the_edge, pass);

    return pass;
}
