/* Generated by Claude Code 2.1.263 (claude-opus-5[1m]) */

/*
 * Unit tests for share/vr.c
 */

#include "test.h"
#include "vr.h"

#define DT (1.0f / 72.0f)

/* Run n frames of camera motion at a constant velocity and yaw rate. */

static float drive(int n, float speed, float yaw_rate)
{
    float p[3] = { 0.0f, 0.0f, 0.0f };
    float a = 0.0f;
    int i;

    for (i = 0; i < n; i++)
    {
        p[0] += speed * DT;
        a    += yaw_rate * DT;

        vr_comfort_step(DT, p, a);
    }

    return vr_comfort_vignette();
}

/*---------------------------------------------------------------------------*/

static void test_vr_still_camera_stays_open(void)
{
    vr_comfort_reset();

    if (vr_comfort_vignette() != 0.0f)
        exit(1);

    /* A camera creeping along must not close the vignette at all. */

    if (drive(200, 0.2f, 1.0f) != 0.0f)
        exit(1);
}

static void test_vr_fast_camera_closes(void)
{
    vr_comfort_reset();

    /* Half a second at speed is plenty for a 0.1s response. */

    if (drive(36, 12.0f, 0.0f) < 0.9f)
        exit(1);
}

static void test_vr_fast_yaw_closes(void)
{
    vr_comfort_reset();

    if (drive(36, 0.0f, 200.0f) < 0.9f)
        exit(1);
}

/* Closing has to beat opening, or the vignette arrives after the motion. */

static void test_vr_closes_faster_than_it_opens(void)
{
    float closed, after;

    vr_comfort_reset();

    closed = drive(10, 12.0f, 0.0f);

    if (closed <= 0.0f)
        exit(1);

    after = drive(10, 0.0f, 0.0f);

    if (!(after > 0.0f && after < closed))
        exit(1);

    /* Ten frames of closing got further than ten frames of opening gave back. */

    if (!(closed > (1.0f - after / closed)))
        exit(1);
}

static void test_vr_reopens_when_the_camera_settles(void)
{
    vr_comfort_reset();

    drive(72, 12.0f, 0.0f);

    if (drive(360, 0.0f, 0.0f) > 0.02f)
        exit(1);
}

/*
 * Yaw is an angle, so it wraps. Crossing due south must not read as a
 * 360-degree flick and slam the vignette shut.
 */

static void test_vr_yaw_wraps(void)
{
    float p[3] = { 0.0f, 0.0f, 0.0f };
    float wrapped, plain;

    /* Two degrees the long way round, across the discontinuity. */

    vr_comfort_reset();
    vr_comfort_step(DT, p,  179.0f);
    vr_comfort_step(DT, p, -179.0f);
    wrapped = vr_comfort_vignette();

    /* The same two degrees, nowhere near it. */

    vr_comfort_reset();
    vr_comfort_step(DT, p, 0.0f);
    vr_comfort_step(DT, p, 2.0f);
    plain = vr_comfort_vignette();

    if (wrapped != plain)
        exit(1);
}

/* A zero or negative timestep must be ignored rather than divided by. */

static void test_vr_ignores_a_stopped_clock(void)
{
    float p[3] = { 0.0f, 0.0f, 0.0f };
    float before;

    vr_comfort_reset();

    before = drive(36, 12.0f, 0.0f);

    p[0] = 1000.0f;

    vr_comfort_step(0.0f,  p, 0.0f);
    vr_comfort_step(-1.0f, p, 0.0f);

    if (vr_comfort_vignette() != before)
        exit(1);
}

/* Starting a level teleports the camera; that is not motion to react to. */

static void test_vr_reset_ignores_the_jump(void)
{
    float p[3] = { 0.0f, 0.0f, 0.0f };

    vr_comfort_reset();

    vr_comfort_step(DT, p, 0.0f);

    p[0] = 500.0f;
    p[2] = -900.0f;

    vr_comfort_reset();
    vr_comfort_step(DT, p, 0.0f);

    if (vr_comfort_vignette() != 0.0f)
        exit(1);
}

/*---------------------------------------------------------------------------*/

int test_vr_comfort_all(void)
{
    int pass = 1;

    RUN_TEST("test_vr_still_camera_stays_open",
             test_vr_still_camera_stays_open, pass);
    RUN_TEST("test_vr_fast_camera_closes", test_vr_fast_camera_closes, pass);
    RUN_TEST("test_vr_fast_yaw_closes", test_vr_fast_yaw_closes, pass);
    RUN_TEST("test_vr_closes_faster_than_it_opens",
             test_vr_closes_faster_than_it_opens, pass);
    RUN_TEST("test_vr_reopens_when_the_camera_settles",
             test_vr_reopens_when_the_camera_settles, pass);
    RUN_TEST("test_vr_yaw_wraps", test_vr_yaw_wraps, pass);
    RUN_TEST("test_vr_ignores_a_stopped_clock",
             test_vr_ignores_a_stopped_clock, pass);
    RUN_TEST("test_vr_reset_ignores_the_jump",
             test_vr_reset_ignores_the_jump, pass);

    return pass;
}
