#!/bin/sh
# Generated by Claude Code 2.1.263 (claude-opus-5[1m])
#
# Build Neverball and Neverputt for Meta Quest, from a clean checkout.
#
#   android/build.sh              debug APKs
#   android/build.sh release      release APKs, signed if a key is set up
#
# Everything is skipped if it has already been done, so this is also the
# quick way to rebuild after editing the game.

set -e

ROOT=$(cd "$(dirname "$0")/.." && pwd)
VARIANT=${1:-debug}

case "$VARIANT" in
    debug)   TASK=assembleDebug ;;
    release) TASK=assembleRelease ;;
    *) echo "usage: $0 [debug|release]" >&2; exit 1 ;;
esac

cd "$ROOT"

# Third-party sources, pinned by fetch-deps.sh.

if [ ! -d android/deps/src/gl4es ]; then
    android/deps/fetch-deps.sh
fi

if [ ! -f android/deps/src/gl4es/lib/libGL.a ]; then
    android/deps/build-gl4es.sh
fi

if [ ! -f android/deps/install/lib/libvorbisfile.a ]; then
    android/deps/build-deps.sh
fi

# The .map files have to be compiled on the host: mapc is a build tool, and
# the root Makefile has no host/target split.

if [ -z "$(find data -name '*.sol' -print -quit)" ]; then
    make -j "$(nproc 2>/dev/null || echo 4)" sols
fi

if [ -z "$(find android/ball/src/main/assets -name '*.zip' -print -quit 2>/dev/null)" ]; then
    android/make-assets.sh
fi

cd android
./gradlew "$TASK"

echo
echo "APKs:"
find ball/build/outputs/apk putt/build/outputs/apk -name '*.apk' -newermt '-1 hour' 2>/dev/null | sort
