#!/bin/sh
# Generated by Claude Code 2.1.263 (claude-opus-5[1m])
#
# Build the game data packages that ship inside the APK.
#
# The packages are ordinary Neverball ZIPs produced by the existing mk/
# machinery, so they are the same artefacts the web build and the download
# system use. They are stored uncompressed in the APK and mounted in place;
# see share/fs_android.c.
#
# SOLs must already be compiled: run "make sols" first.

set -e

ROOT=$(cd "$(dirname "$0")/.." && pwd)
ASSETS="$ROOT/android/app/src/main/assets"

SETS="easy medium hard misc"

cd "$ROOT"

if [ -z "$(find data -name '*.sol' -print -quit)" ]; then
    echo "No SOLs found. Run 'make sols' first." >&2
    exit 1
fi

mkdir -p "$ASSETS"
rm -f "$ASSETS"/*.zip "$ASSETS"/*.manifest.txt

# SKIP_MP3 leaves out the MP3 twins of every Ogg, which exist only because
# Safari cannot decode Ogg. Android decodes Ogg natively via libvorbisfile.

make -f mk/package-base.mk OUTPUT_DIR="$ASSETS" SKIP_MP3=1 package-only

for s in $SETS; do
    make -f mk/package-levelset.mk \
        PACKAGE_ID="set-$s" \
        SET_FILE="./data/set-$s.txt" \
        DATA_DIR=./data \
        ADDON_SET=0 \
        OUTPUT_DIR="$ASSETS" \
        SKIP_MP3=1 \
        package
done

rm -f "$ASSETS"/*.manifest.txt

echo
echo "Assets:"
ls -la "$ASSETS"
