#!/bin/sh
# Generated by Claude Code 2.1.263 (claude-opus-5[1m])
#
# Build the game data packages that ship inside the two APKs.
#
# The packages are ordinary Neverball ZIPs produced by the existing mk/
# machinery, so they are the same artefacts the web build and the download
# system use. They are stored uncompressed in the APK and mounted in place;
# see share/fs_android.c.
#
# SOLs must already be compiled: run "make sols" first.

set -e

ROOT=$(cd "$(dirname "$0")/.." && pwd)
ASSETS_BALL="$ROOT/android/ball/src/main/assets"
ASSETS_PUTT="$ROOT/android/putt/src/main/assets"

# Every set data/sets.txt names. Leaving any of them out is not free: the
# game lists what it can load, so a missing one is silently absent from the
# menu and noisy in the log.

SETS="easy medium hard misc mym mym2 fwp tones"

cd "$ROOT"

if [ -z "$(find data -name '*.sol' -print -quit)" ]; then
    echo "No SOLs found. Run 'make sols' first." >&2
    exit 1
fi

mkdir -p "$ASSETS_BALL" "$ASSETS_PUTT"
rm -f "$ASSETS_BALL"/*.zip "$ASSETS_BALL"/*.manifest.txt
rm -f "$ASSETS_PUTT"/*.zip "$ASSETS_PUTT"/*.manifest.txt

# SKIP_MP3 leaves out the MP3 twins of every Ogg, which exist only because
# Safari cannot decode Ogg. Android decodes Ogg natively via libvorbisfile.

make -f mk/package-base.mk OUTPUT_DIR="$ASSETS_BALL" SKIP_MP3=1 package-only

for s in $SETS; do
    make -f mk/package-levelset.mk \
        PACKAGE_ID="set-$s" \
        SET_FILE="./data/set-$s.txt" \
        DATA_DIR=./data \
        ADDON_SET=0 \
        OUTPUT_DIR="$ASSETS_BALL" \
        SKIP_MP3=1 \
        package
done

# Neverputt is one package: its courses are not downloadable content, so
# there is nothing to gain from splitting them up.

make -f mk/package-base-putt.mk OUTPUT_DIR="$ASSETS_PUTT" SKIP_MP3=1 package-only

rm -f "$ASSETS_BALL"/*.manifest.txt "$ASSETS_PUTT"/*.manifest.txt

echo
echo "Neverball assets:"
ls -la "$ASSETS_BALL"
echo
echo "Neverputt assets:"
ls -la "$ASSETS_PUTT"
