#!/bin/sh
# Generated by Claude Code 2.1.263 (claude-opus-5[1m])
#
# Create a signing key for release builds.
#
# Android refuses to install an unsigned APK, so a release build needs a key
# even to be sideloaded. The key and the properties file that points at it
# are both ignored by git: a signing key is a credential, and this one is
# yours alone. Keep it. Losing it means the next release cannot be installed
# as an update over this one.

set -e

DIR=$(cd "$(dirname "$0")" && pwd)
STORE="$DIR/neverball-release.keystore"
PROPS="$DIR/keystore.properties"

if [ -f "$STORE" ]; then
    echo "$STORE already exists; refusing to overwrite it." >&2
    exit 1
fi

if [ -z "$STORE_PASSWORD" ]; then
    printf 'Password for the new key: '
    stty -echo
    read STORE_PASSWORD
    stty echo
    printf '\n'
fi

if [ -z "$STORE_PASSWORD" ]; then
    echo "A password is required." >&2
    exit 1
fi

keytool -genkeypair \
    -keystore "$STORE" \
    -storepass "$STORE_PASSWORD" \
    -keypass "$STORE_PASSWORD" \
    -alias neverball \
    -keyalg RSA \
    -keysize 4096 \
    -validity 10950 \
    -dname 'CN=Neverball, OU=Quest port'

cat > "$PROPS" <<PROPS_EOF
storeFile=$STORE
storePassword=$STORE_PASSWORD
keyAlias=neverball
keyPassword=$STORE_PASSWORD
PROPS_EOF

chmod 600 "$PROPS" "$STORE"

echo
echo "Wrote $STORE and $PROPS."
echo "Both are ignored by git. Back them up somewhere you will still have"
echo "them when the next release is built."
