/* Generated by Claude Code 2.1.263 (claude-opus-5[1m]) */

/*
 * Milestone-0 spike for the Neverball Quest port.
 *
 * This is throwaway code with one job: prove, on the device, that the four
 * unproven pieces of the port work together before any Neverball source is
 * touched.
 *
 *   1. SDL2's SDLActivity shell coexists with an OpenXR session, and the
 *      EGL context SDL created is acceptable to xrCreateSession.
 *   2. gl4es translates fixed-function OpenGL 1.x to GLES on Android, and
 *      reports the extensions share/glext.c:147-168 asserts at startup.
 *   3. gl4es renders correctly into an OpenXR swapchain image's FBO and does
 *      not steal the binding back.
 *   4. The two renderer features most likely to fail under translation --
 *      the GL_COMBINE texenv chain (share/geom.c:104-207) and the stencil
 *      reflection pass (ball/game_draw.c:520-556) -- survive.
 *
 * Everything is logged to "NeverballSpike" so the run can be judged from
 * adb logcat alone.
 */

#include <SDL.h>
#include <SDL_main.h>
#include <SDL_system.h>

#include <EGL/egl.h>

/* gl4es declares GL 1.2+ entry points (VBOs, multitexture, FBOs) in its
 * glext.h, gated on GL_GLEXT_PROTOTYPES. share/glext.h will need the same
 * treatment for the Android target. */
#define GL_GLEXT_PROTOTYPES
#include <GL/gl.h>
#include <GL/glext.h>
#include <gl4esinit.h>

#include <android/log.h>
#include <jni.h>

#define XR_USE_PLATFORM_ANDROID
#define XR_USE_GRAPHICS_API_OPENGL_ES
#include <openxr/openxr.h>
#include <openxr/openxr_platform.h>

#include <math.h>
#include <string.h>
#include <stdlib.h>

/*---------------------------------------------------------------------------*/


/*---------------------------------------------------------------------------*/

#define TAG "NeverballSpike"

#define logi(...) __android_log_print(ANDROID_LOG_INFO,  TAG, __VA_ARGS__)
#define loge(...) __android_log_print(ANDROID_LOG_ERROR, TAG, __VA_ARGS__)

#define EYE_COUNT 2

/* Report an OpenXR failure and bail out of the calling function. */

#define XR_TRY(expr)                                                    \
    do {                                                                \
        XrResult res_ = (expr);                                         \
        if (XR_FAILED(res_)) {                                          \
            loge("%s failed (%d) at %s:%d", #expr, (int) res_,          \
                 __FILE__, __LINE__);                                   \
            return 0;                                                   \
        }                                                               \
    } while (0)

/*---------------------------------------------------------------------------*/

struct eye_swapchain
{
    XrSwapchain              handle;
    uint32_t                 image_count;
    XrSwapchainImageOpenGLESKHR *images;
    GLuint                  *fbos;
    GLuint                   depth;
    int32_t                  w, h;
};

static SDL_Window   *window;
static SDL_GLContext gl_context;

static XrInstance    xr_instance  = XR_NULL_HANDLE;
static XrSystemId    xr_system    = XR_NULL_SYSTEM_ID;
static XrSession     xr_session   = XR_NULL_HANDLE;
static XrSpace       xr_space     = XR_NULL_HANDLE;
static XrSessionState xr_state    = XR_SESSION_STATE_UNKNOWN;

static struct eye_swapchain xr_eye[EYE_COUNT];

static XrView                    xr_views[EYE_COUNT];
static XrViewConfigurationView   xr_config_views[EYE_COUNT];

static XrTime xr_display_time;
static int    xr_running;
static int    xr_should_render;

/* Input. */

static XrActionSet xr_actions;
static XrAction    act_tilt;         /* left thumbstick, Vector2f */
static XrAction    act_select;       /* trigger, boolean          */
static XrAction    act_grip_pose;    /* right grip, pose          */
static XrSpace     xr_grip_space;

static GLuint tex_checker;
static GLuint tex_gradient;
static GLuint vbo_quad;

/*---------------------------------------------------------------------------*/
/* Small matrix helpers. Column-major, same convention as share/video.c.     */

static void m_identity(float *m)
{
    memset(m, 0, 16 * sizeof (float));
    m[0] = m[5] = m[10] = m[15] = 1.0f;
}

/*
 * Asymmetric projection from an OpenXR field of view. The four angles are
 * signed and independent, which is exactly what share/video.c:522's
 * symmetric fov-and-aspect formula cannot express -- the reason hmd_persp()
 * exists as a bypass.
 */

static void m_projection(float *m, const XrFovf *fov, float n, float f)
{
    const float l = tanf(fov->angleLeft);
    const float r = tanf(fov->angleRight);
    const float d = tanf(fov->angleDown);
    const float u = tanf(fov->angleUp);

    const float w = r - l;
    const float h = u - d;

    memset(m, 0, 16 * sizeof (float));

    m[0]  = 2.0f / w;
    m[5]  = 2.0f / h;
    m[8]  = (r + l) / w;
    m[9]  = (u + d) / h;
    m[10] = -(f + n) / (f - n);
    m[11] = -1.0f;
    m[14] = -(2.0f * f * n) / (f - n);
}

/* Inverse of a rigid pose, as a view matrix. */

static void m_view_from_pose(float *m, const XrPosef *p)
{
    const float x = p->orientation.x;
    const float y = p->orientation.y;
    const float z = p->orientation.z;
    const float w = p->orientation.w;

    float R[9];

    R[0] = 1.0f - 2.0f * (y * y + z * z);
    R[1] =        2.0f * (x * y + z * w);
    R[2] =        2.0f * (x * z - y * w);

    R[3] =        2.0f * (x * y - z * w);
    R[4] = 1.0f - 2.0f * (x * x + z * z);
    R[5] =        2.0f * (y * z + x * w);

    R[6] =        2.0f * (x * z + y * w);
    R[7] =        2.0f * (y * z - x * w);
    R[8] = 1.0f - 2.0f * (x * x + y * y);

    /* Transpose the rotation and apply it to the negated translation. */

    m_identity(m);

    m[0] = R[0]; m[4] = R[1]; m[8]  = R[2];
    m[1] = R[3]; m[5] = R[4]; m[9]  = R[5];
    m[2] = R[6]; m[6] = R[7]; m[10] = R[8];

    m[12] = -(m[0] * p->position.x + m[4] * p->position.y + m[8]  * p->position.z);
    m[13] = -(m[1] * p->position.x + m[5] * p->position.y + m[9]  * p->position.z);
    m[14] = -(m[2] * p->position.x + m[6] * p->position.y + m[10] * p->position.z);
}

/*---------------------------------------------------------------------------*/
/* gl4es setup                                                               */

static void gl4es_main_fb_size(int *w, int *h)
{
    /* gl4es needs a notion of the default framebuffer. We never draw to it,
     * so report the per-eye swapchain size. */

    *w = xr_eye[0].w ? xr_eye[0].w : 1024;
    *h = xr_eye[0].h ? xr_eye[0].h : 1024;
}

/*
 * share/glext.c:147-168 hard-asserts these three before setting up its
 * function pointers. If gl4es does not advertise them the real game will
 * start and then crash on a null pointer, so check here where it is cheap
 * to diagnose.
 */

static int check_gl_extensions(void)
{
    static const char *required[] = {
        "GL_ARB_multitexture",
        "GL_ARB_vertex_buffer_object",
        "GL_ARB_point_parameters",
    };

    const char *ext = (const char *) glGetString(GL_EXTENSIONS);

    int ok = 1;
    size_t i;

    logi("GL_VENDOR   : %s", (const char *) glGetString(GL_VENDOR));
    logi("GL_RENDERER : %s", (const char *) glGetString(GL_RENDERER));
    logi("GL_VERSION  : %s", (const char *) glGetString(GL_VERSION));

    if (!ext)
    {
        loge("glGetString(GL_EXTENSIONS) returned NULL");
        return 0;
    }

    for (i = 0; i < sizeof (required) / sizeof (*required); i++)
    {
        /* glext_check() in share/glext.c matches without the GL_ prefix. */

        const char *name = required[i] + 3;

        if (strstr(ext, name))
            logi("extension ok: %s", required[i]);
        else
        {
            loge("extension MISSING: %s", required[i]);
            ok = 0;
        }
    }

    if (strstr(ext, "ARB_framebuffer_object"))
        logi("extension ok: GL_ARB_framebuffer_object");
    else
        logi("note: ARB_framebuffer_object absent (only hmd_common.c needs it)");

    {
        GLint units = 0;
        glGetIntegerv(GL_MAX_TEXTURE_UNITS, &units);
        logi("GL_MAX_TEXTURE_UNITS = %d (share/geom.c needs 2)", (int) units);

        if (units < 2)
            ok = 0;
    }

    return ok;
}

/*---------------------------------------------------------------------------*/
/* Procedural textures, so the spike needs no assets.                        */

static GLuint make_checker(int size, int cell)
{
    unsigned char *p = malloc((size_t) size * size * 4);
    GLuint t = 0;
    int x, y;

    if (!p) return 0;

    for (y = 0; y < size; y++)
        for (x = 0; x < size; x++)
        {
            const int on = ((x / cell) + (y / cell)) & 1;
            unsigned char *q = p + 4 * (y * size + x);

            q[0] = on ? 230 : 40;
            q[1] = on ? 230 : 60;
            q[2] = on ? 240 : 90;
            q[3] = 255;
        }

    glGenTextures(1, &t);
    glBindTexture(GL_TEXTURE_2D, t);
    glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, size, size, 0,
                 GL_RGBA, GL_UNSIGNED_BYTE, p);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);

    free(p);

    return t;
}

static GLuint make_gradient(int size)
{
    unsigned char *p = malloc((size_t) size * size * 4);
    GLuint t = 0;
    int x, y;

    if (!p) return 0;

    for (y = 0; y < size; y++)
        for (x = 0; x < size; x++)
        {
            unsigned char *q = p + 4 * (y * size + x);

            q[0] = (unsigned char) (255 * x / size);
            q[1] = (unsigned char) (255 * y / size);
            q[2] = 128;
            q[3] = (unsigned char) (255 * x / size);
        }

    glGenTextures(1, &t);
    glBindTexture(GL_TEXTURE_2D, t);
    glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, size, size, 0,
                 GL_RGBA, GL_UNSIGNED_BYTE, p);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);

    free(p);

    return t;
}

/*
 * A unit quad in the XZ plane, interleaved position/normal/texcoord, in a
 * VBO. Neverball's geometry is all VBO-backed like this (share/solid_draw.c),
 * so this exercises the same path.
 */

static void make_quad_vbo(void)
{
    static const GLfloat v[] = {
        /*  px    py    pz     nx   ny   nz     s     t  */
        -1.0f, 0.0f, -1.0f,  0.0f, 1.0f, 0.0f,  0.0f, 0.0f,
         1.0f, 0.0f, -1.0f,  0.0f, 1.0f, 0.0f,  1.0f, 0.0f,
        -1.0f, 0.0f,  1.0f,  0.0f, 1.0f, 0.0f,  0.0f, 1.0f,
         1.0f, 0.0f,  1.0f,  0.0f, 1.0f, 0.0f,  1.0f, 1.0f,
    };

    glGenBuffers(1, &vbo_quad);
    glBindBuffer(GL_ARRAY_BUFFER, vbo_quad);
    glBufferData(GL_ARRAY_BUFFER, sizeof (v), v, GL_STATIC_DRAW);
    glBindBuffer(GL_ARRAY_BUFFER, 0);
}

static void draw_quad_vbo(void)
{
    glBindBuffer(GL_ARRAY_BUFFER, vbo_quad);

    glEnableClientState(GL_VERTEX_ARRAY);
    glEnableClientState(GL_NORMAL_ARRAY);
    glEnableClientState(GL_TEXTURE_COORD_ARRAY);

    glVertexPointer  (3, GL_FLOAT, 8 * sizeof (GLfloat), (void *) 0);
    glNormalPointer  (   GL_FLOAT, 8 * sizeof (GLfloat), (void *) (3 * sizeof (GLfloat)));
    glTexCoordPointer(2, GL_FLOAT, 8 * sizeof (GLfloat), (void *) (6 * sizeof (GLfloat)));

    glDrawArrays(GL_TRIANGLE_STRIP, 0, 4);

    glDisableClientState(GL_TEXTURE_COORD_ARRAY);
    glDisableClientState(GL_NORMAL_ARRAY);
    glDisableClientState(GL_VERTEX_ARRAY);

    glBindBuffer(GL_ARRAY_BUFFER, 0);
}

/*---------------------------------------------------------------------------*/
/* The two renderer features most at risk under translation.                 */

/*
 * A two-unit GL_COMBINE chain shaped like share/geom.c:104-207, which builds
 * Neverball's ball shadow: unit 0 modulates by one-minus-alpha, unit 1
 * interpolates between the result and the primary colour using the second
 * texture's alpha as the weight. GL_INTERPOLATE with SRC2_RGB = GL_TEXTURE
 * is the least-travelled path in any texenv-to-shader translator.
 *
 * Correct result: a quad tinted from the gradient, blended against red, with
 * a visible checker pattern. Wrong result: flat white, flat red, or black.
 */

static void draw_combine_quad(void)
{
    glColor4f(1.0f, 0.2f, 0.2f, 1.0f);

    glActiveTexture(GL_TEXTURE0);
    glEnable(GL_TEXTURE_2D);
    glBindTexture(GL_TEXTURE_2D, tex_gradient);

    glTexEnvi(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_COMBINE);
    glTexEnvi(GL_TEXTURE_ENV, GL_COMBINE_RGB,      GL_MODULATE);
    glTexEnvi(GL_TEXTURE_ENV, GL_SRC0_RGB,         GL_PRIMARY_COLOR);
    glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND0_RGB,     GL_SRC_COLOR);
    glTexEnvi(GL_TEXTURE_ENV, GL_SRC1_RGB,         GL_TEXTURE);
    glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND1_RGB,     GL_ONE_MINUS_SRC_ALPHA);

    glActiveTexture(GL_TEXTURE1);
    glEnable(GL_TEXTURE_2D);
    glBindTexture(GL_TEXTURE_2D, tex_checker);

    glTexEnvi(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_COMBINE);
    glTexEnvi(GL_TEXTURE_ENV, GL_COMBINE_RGB,      GL_INTERPOLATE);
    glTexEnvi(GL_TEXTURE_ENV, GL_SRC0_RGB,         GL_PREVIOUS);
    glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND0_RGB,     GL_SRC_COLOR);
    glTexEnvi(GL_TEXTURE_ENV, GL_SRC1_RGB,         GL_TEXTURE);
    glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND1_RGB,     GL_SRC_COLOR);
    glTexEnvi(GL_TEXTURE_ENV, GL_SRC2_RGB,         GL_TEXTURE);
    glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND2_RGB,     GL_SRC_ALPHA);

    /* Unit 1 needs coordinates too; reuse unit 0's array. */

    glClientActiveTexture(GL_TEXTURE1);
    glBindBuffer(GL_ARRAY_BUFFER, vbo_quad);
    glEnableClientState(GL_TEXTURE_COORD_ARRAY);
    glTexCoordPointer(2, GL_FLOAT, 8 * sizeof (GLfloat),
                      (void *) (6 * sizeof (GLfloat)));

    glClientActiveTexture(GL_TEXTURE0);

    draw_quad_vbo();

    glClientActiveTexture(GL_TEXTURE1);
    glDisableClientState(GL_TEXTURE_COORD_ARRAY);
    glBindBuffer(GL_ARRAY_BUFFER, 0);
    glClientActiveTexture(GL_TEXTURE0);

    /* Restore. */

    glActiveTexture(GL_TEXTURE1);
    glTexEnvi(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_MODULATE);
    glDisable(GL_TEXTURE_2D);

    glActiveTexture(GL_TEXTURE0);
    glTexEnvi(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_MODULATE);

    glColor4f(1.0f, 1.0f, 1.0f, 1.0f);
}

/*
 * A stencil mask plus a mirrored draw, shaped like the reflection pass at
 * ball/game_draw.c:520-556. This also proves the OpenXR swapchain FBO really
 * has a usable stencil attachment.
 *
 * Correct result: the mirrored checker quad appears ONLY inside the masked
 * square. Wrong result: it covers everything, or nothing.
 */

static void draw_stencil_test(void)
{
    glEnable(GL_STENCIL_TEST);
    {
        /* Punch the mask. */

        glStencilFunc(GL_ALWAYS, 1, 0xFFFFFFFF);
        glStencilOp(GL_REPLACE, GL_REPLACE, GL_REPLACE);
        glColorMask(GL_FALSE, GL_FALSE, GL_FALSE, GL_FALSE);
        glDepthMask(GL_FALSE);

        glPushMatrix();
        {
            glTranslatef(0.0f, 0.001f, 0.0f);
            glScalef(0.5f, 1.0f, 0.5f);
            draw_quad_vbo();
        }
        glPopMatrix();

        glDepthMask(GL_TRUE);
        glColorMask(GL_TRUE, GL_TRUE, GL_TRUE, GL_TRUE);

        /* Draw only inside it, mirrored, exactly as the reflection does. */

        glStencilOp(GL_KEEP, GL_KEEP, GL_KEEP);
        glStencilFunc(GL_EQUAL, 1, 0xFFFFFFFF);

        glFrontFace(GL_CW);
        glPushMatrix();
        {
            glScalef(1.0f, -1.0f, 1.0f);
            glTranslatef(0.0f, -0.6f, 0.0f);

            glBindTexture(GL_TEXTURE_2D, tex_checker);
            draw_quad_vbo();
        }
        glPopMatrix();
        glFrontFace(GL_CCW);

        glStencilFunc(GL_ALWAYS, 0, 0xFFFFFFFF);
    }
    glDisable(GL_STENCIL_TEST);
}

/* The scene, drawn once per eye through gl4es fixed-function calls. */

static void draw_scene(float t)
{
    static const GLfloat light_p[] = { 0.4f, 1.0f, 0.6f, 0.0f };
    static const GLfloat light_d[] = { 1.0f, 1.0f, 1.0f, 1.0f };
    static const GLfloat light_a[] = { 0.3f, 0.3f, 0.35f, 1.0f };

    glEnable(GL_DEPTH_TEST);
    glEnable(GL_CULL_FACE);

    /* Fixed-function lighting, as share/solid_draw.c uses. */

    glEnable(GL_LIGHTING);
    glEnable(GL_LIGHT0);
    glLightfv(GL_LIGHT0, GL_POSITION, light_p);
    glLightfv(GL_LIGHT0, GL_DIFFUSE,  light_d);
    glLightfv(GL_LIGHT0, GL_AMBIENT,  light_a);

    glEnable(GL_TEXTURE_2D);
    glBindTexture(GL_TEXTURE_2D, tex_checker);

    /* A ground plane one metre across, half a metre in front, at waist
     * height -- roughly where the diorama will sit. */

    glPushMatrix();
    {
        glTranslatef(0.0f, 1.0f, -0.6f);
        glScalef(0.5f, 0.5f, 0.5f);

        glPushMatrix();
        {
            glRotatef(t * 20.0f, 0.0f, 1.0f, 0.0f);
            draw_quad_vbo();
        }
        glPopMatrix();

        /* Texenv combiner test, floating above the ground plane. */

        glDisable(GL_LIGHTING);
        glPushMatrix();
        {
            glTranslatef(-1.2f, 0.4f, 0.0f);
            glRotatef(-70.0f, 1.0f, 0.0f, 0.0f);
            glScalef(0.4f, 0.4f, 0.4f);
            draw_combine_quad();
        }
        glPopMatrix();

        /* Stencil test, on the other side. */

        glPushMatrix();
        {
            glTranslatef(1.2f, 0.4f, 0.0f);
            glRotatef(-70.0f, 1.0f, 0.0f, 0.0f);
            glScalef(0.4f, 0.4f, 0.4f);
            draw_stencil_test();
        }
        glPopMatrix();
        glEnable(GL_LIGHTING);
    }
    glPopMatrix();

    glDisable(GL_LIGHTING);
    glDisable(GL_TEXTURE_2D);
}

/*---------------------------------------------------------------------------*/
/* SDL and gl4es                                                             */

/*
 * Create the window and GL context exactly the way share/video.c:265-282
 * already does, then hand OpenXR the EGL objects SDL made. Rolling our own
 * EGL would mean reimplementing the proven ordering of
 * set_getprocaddress()/initialize_gl4es() by hand; if SDL's surface
 * lifecycle turns out to invalidate the context on focus loss, that is the
 * fallback, and this spike is where we find out.
 */

static int init_sdl_gl(void)
{
    if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_AUDIO) != 0)
    {
        loge("SDL_Init: %s", SDL_GetError());
        return 0;
    }

    SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_ES);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 2);

    /* Plain config: the depth and stencil we care about live on the
     * swapchain FBOs, not on this surface. */

    SDL_GL_SetAttribute(SDL_GL_RED_SIZE,     8);
    SDL_GL_SetAttribute(SDL_GL_GREEN_SIZE,   8);
    SDL_GL_SetAttribute(SDL_GL_BLUE_SIZE,    8);
    SDL_GL_SetAttribute(SDL_GL_ALPHA_SIZE,   8);
    SDL_GL_SetAttribute(SDL_GL_DEPTH_SIZE,   0);
    SDL_GL_SetAttribute(SDL_GL_STENCIL_SIZE, 0);
    SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER, 1);

    if (!(window = SDL_CreateWindow("Neverball", SDL_WINDOWPOS_UNDEFINED,
                                    SDL_WINDOWPOS_UNDEFINED, 16, 16,
                                    SDL_WINDOW_OPENGL | SDL_WINDOW_FULLSCREEN)))
    {
        loge("SDL_CreateWindow: %s", SDL_GetError());
        return 0;
    }

    if (!(gl_context = SDL_GL_CreateContext(window)))
    {
        loge("SDL_GL_CreateContext: %s", SDL_GetError());
        return 0;
    }

    /* The XR compositor paces us; never block on the window's swap. */

    SDL_GL_SetSwapInterval(0);

    /* Bring up gl4es, mirroring share/video.c:279-285. */

    set_getprocaddress((void *(*)(const char *)) SDL_GL_GetProcAddress);
    set_getmainfbsize(gl4es_main_fb_size);
    initialize_gl4es();

    return check_gl_extensions();
}

/*---------------------------------------------------------------------------*/
/* OpenXR                                                                    */

static int xr_init_loader(void)
{
    PFN_xrInitializeLoaderKHR pfn = NULL;

    JNIEnv  *env = SDL_AndroidGetJNIEnv();
    JavaVM  *vm  = NULL;
    jobject  activity;

    XrLoaderInitInfoAndroidKHR info;

    if (!env)
    {
        loge("SDL_AndroidGetJNIEnv returned NULL");
        return 0;
    }

    (*env)->GetJavaVM(env, &vm);

    activity = (jobject) SDL_AndroidGetActivity();

    XR_TRY(xrGetInstanceProcAddr(XR_NULL_HANDLE, "xrInitializeLoaderKHR",
                                 (PFN_xrVoidFunction *) &pfn));

    memset(&info, 0, sizeof (info));
    info.type               = XR_TYPE_LOADER_INIT_INFO_ANDROID_KHR;
    info.applicationVM      = vm;
    info.applicationContext = activity;

    XR_TRY(pfn((const XrLoaderInitInfoBaseHeaderKHR *) &info));

    logi("OpenXR loader initialised");

    return 1;
}

static int xr_has_extension(const XrExtensionProperties *p, uint32_t n,
                            const char *name)
{
    uint32_t i;

    for (i = 0; i < n; i++)
        if (strcmp(p[i].extensionName, name) == 0)
            return 1;

    return 0;
}

static int xr_local_floor;

static int xr_init_instance(void)
{
    XrExtensionProperties *props = NULL;
    uint32_t count = 0, i;

    const char *enabled[4];
    uint32_t    enabled_count = 0;

    XrInstanceCreateInfo        create;
    XrInstanceCreateInfoAndroidKHR android;
    XrSystemGetInfo             sys;

    JNIEnv *env = SDL_AndroidGetJNIEnv();
    JavaVM *vm  = NULL;

    (*env)->GetJavaVM(env, &vm);

    XR_TRY(xrEnumerateInstanceExtensionProperties(NULL, 0, &count, NULL));

    props = calloc(count, sizeof (*props));
    if (!props) return 0;

    for (i = 0; i < count; i++)
        props[i].type = XR_TYPE_EXTENSION_PROPERTIES;

    XR_TRY(xrEnumerateInstanceExtensionProperties(NULL, count, &count, props));

    logi("OpenXR runtime offers %u extensions", count);

    if (!xr_has_extension(props, count, XR_KHR_OPENGL_ES_ENABLE_EXTENSION_NAME))
    {
        loge("runtime lacks %s -- OpenGL ES is not available",
             XR_KHR_OPENGL_ES_ENABLE_EXTENSION_NAME);
        free(props);
        return 0;
    }

    enabled[enabled_count++] = XR_KHR_OPENGL_ES_ENABLE_EXTENSION_NAME;
    enabled[enabled_count++] = XR_KHR_ANDROID_CREATE_INSTANCE_EXTENSION_NAME;

    if (xr_has_extension(props, count, XR_EXT_LOCAL_FLOOR_EXTENSION_NAME))
    {
        enabled[enabled_count++] = XR_EXT_LOCAL_FLOOR_EXTENSION_NAME;
        xr_local_floor = 1;
        logi("XR_EXT_local_floor available");
    }

    free(props);

    memset(&android, 0, sizeof (android));
    android.type            = XR_TYPE_INSTANCE_CREATE_INFO_ANDROID_KHR;
    android.applicationVM   = vm;
    android.applicationActivity = (jobject) SDL_AndroidGetActivity();

    memset(&create, 0, sizeof (create));
    create.type = XR_TYPE_INSTANCE_CREATE_INFO;
    create.next = &android;
    create.enabledExtensionCount = enabled_count;
    create.enabledExtensionNames = enabled;
    strcpy(create.applicationInfo.applicationName, "Neverball");
    strcpy(create.applicationInfo.engineName, "Neverball");
    create.applicationInfo.applicationVersion = 1;
    create.applicationInfo.engineVersion      = 1;
    create.applicationInfo.apiVersion         = XR_CURRENT_API_VERSION;

    XR_TRY(xrCreateInstance(&create, &xr_instance));

    memset(&sys, 0, sizeof (sys));
    sys.type       = XR_TYPE_SYSTEM_GET_INFO;
    sys.formFactor = XR_FORM_FACTOR_HEAD_MOUNTED_DISPLAY;

    XR_TRY(xrGetSystem(xr_instance, &sys, &xr_system));

    {
        XrInstanceProperties ip;
        memset(&ip, 0, sizeof (ip));
        ip.type = XR_TYPE_INSTANCE_PROPERTIES;

        if (XR_SUCCEEDED(xrGetInstanceProperties(xr_instance, &ip)))
            logi("OpenXR runtime: %s", ip.runtimeName);
    }

    return 1;
}

static int xr_init_session(void)
{
    PFN_xrGetOpenGLESGraphicsRequirementsKHR pfn = NULL;
    XrGraphicsRequirementsOpenGLESKHR req;

    XrGraphicsBindingOpenGLESAndroidKHR bind;
    XrSessionCreateInfo create;
    XrReferenceSpaceCreateInfo space;

    XrReferenceSpaceType *types = NULL;
    uint32_t type_count = 0, i;
    XrReferenceSpaceType chosen = XR_REFERENCE_SPACE_TYPE_LOCAL;

    EGLDisplay dpy = eglGetCurrentDisplay();
    EGLContext ctx = eglGetCurrentContext();
    EGLConfig  cfg = NULL;
    EGLint     cfg_id = 0, n = 0;

    if (dpy == EGL_NO_DISPLAY || ctx == EGL_NO_CONTEXT)
    {
        loge("no current EGL context to bind (dpy=%p ctx=%p)", dpy, ctx);
        return 0;
    }

    /* Recover the EGLConfig SDL chose, by id. */

    if (!eglQueryContext(dpy, ctx, EGL_CONFIG_ID, &cfg_id))
    {
        loge("eglQueryContext(EGL_CONFIG_ID) failed");
        return 0;
    }

    {
        const EGLint attrs[] = { EGL_CONFIG_ID, cfg_id, EGL_NONE };

        if (!eglChooseConfig(dpy, attrs, &cfg, 1, &n) || n != 1)
        {
            loge("could not recover EGLConfig %d", (int) cfg_id);
            return 0;
        }
    }

    logi("EGL display=%p context=%p config_id=%d", dpy, ctx, (int) cfg_id);

    /* The spec requires querying graphics requirements before creating the
     * session, even though we only log the result. */

    XR_TRY(xrGetInstanceProcAddr(xr_instance,
                                 "xrGetOpenGLESGraphicsRequirementsKHR",
                                 (PFN_xrVoidFunction *) &pfn));

    memset(&req, 0, sizeof (req));
    req.type = XR_TYPE_GRAPHICS_REQUIREMENTS_OPENGL_ES_KHR;

    XR_TRY(pfn(xr_instance, xr_system, &req));

    logi("OpenXR wants GLES between %d.%d and %d.%d",
         XR_VERSION_MAJOR(req.minApiVersionSupported),
         XR_VERSION_MINOR(req.minApiVersionSupported),
         XR_VERSION_MAJOR(req.maxApiVersionSupported),
         XR_VERSION_MINOR(req.maxApiVersionSupported));

    memset(&bind, 0, sizeof (bind));
    bind.type    = XR_TYPE_GRAPHICS_BINDING_OPENGL_ES_ANDROID_KHR;
    bind.display = dpy;
    bind.config  = cfg;
    bind.context = ctx;

    memset(&create, 0, sizeof (create));
    create.type     = XR_TYPE_SESSION_CREATE_INFO;
    create.next     = &bind;
    create.systemId = xr_system;

    XR_TRY(xrCreateSession(xr_instance, &create, &xr_session));

    logi("XR session created");

    /* Pick the best available reference space: a floor-relative origin is
     * what the diorama anchor wants. */

    XR_TRY(xrEnumerateReferenceSpaces(xr_session, 0, &type_count, NULL));

    types = calloc(type_count, sizeof (*types));
    if (!types) return 0;

    XR_TRY(xrEnumerateReferenceSpaces(xr_session, type_count, &type_count, types));

    for (i = 0; i < type_count; i++)
    {
        if (xr_local_floor &&
            types[i] == XR_REFERENCE_SPACE_TYPE_LOCAL_FLOOR_EXT)
        {
            chosen = types[i];
            break;
        }
        if (types[i] == XR_REFERENCE_SPACE_TYPE_STAGE &&
            chosen != XR_REFERENCE_SPACE_TYPE_LOCAL_FLOOR_EXT)
            chosen = types[i];
    }

    free(types);

    logi("reference space: %d", (int) chosen);

    memset(&space, 0, sizeof (space));
    space.type                 = XR_TYPE_REFERENCE_SPACE_CREATE_INFO;
    space.referenceSpaceType   = chosen;
    space.poseInReferenceSpace.orientation.w = 1.0f;

    XR_TRY(xrCreateReferenceSpace(xr_session, &space, &xr_space));

    return 1;
}

static int xr_init_swapchains(void)
{
    uint32_t count = 0, i, j;
    int64_t *formats = NULL;
    int64_t  chosen  = 0;

    XR_TRY(xrEnumerateViewConfigurationViews(
               xr_instance, xr_system,
               XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO,
               0, &count, NULL));

    if (count != EYE_COUNT)
    {
        loge("expected %d views, runtime reports %u", EYE_COUNT, count);
        return 0;
    }

    for (i = 0; i < EYE_COUNT; i++)
        xr_config_views[i].type = XR_TYPE_VIEW_CONFIGURATION_VIEW;

    XR_TRY(xrEnumerateViewConfigurationViews(
               xr_instance, xr_system,
               XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO,
               count, &count, xr_config_views));

    /* Pick a colour format. */

    XR_TRY(xrEnumerateSwapchainFormats(xr_session, 0, &count, NULL));

    formats = calloc(count, sizeof (*formats));
    if (!formats) return 0;

    XR_TRY(xrEnumerateSwapchainFormats(xr_session, count, &count, formats));

    for (i = 0; i < count; i++)
    {
        if (formats[i] == 0x8C43)       /* GL_SRGB8_ALPHA8 */
        {
            chosen = formats[i];
            break;
        }
        if (formats[i] == 0x8058 && !chosen)   /* GL_RGBA8 */
            chosen = formats[i];
    }

    free(formats);

    if (!chosen)
    {
        loge("no usable swapchain format");
        return 0;
    }

    logi("swapchain format 0x%llx", (unsigned long long) chosen);

    for (i = 0; i < EYE_COUNT; i++)
    {
        struct eye_swapchain *e = &xr_eye[i];
        XrSwapchainCreateInfo info;

        /* Render at 70% of recommended: a one-metre diorama does not need
         * full panel resolution, and this is the cheapest perf dial. */

        e->w = (int32_t) (xr_config_views[i].recommendedImageRectWidth  * 7 / 10);
        e->h = (int32_t) (xr_config_views[i].recommendedImageRectHeight * 7 / 10);

        memset(&info, 0, sizeof (info));
        info.type        = XR_TYPE_SWAPCHAIN_CREATE_INFO;
        info.usageFlags  = XR_SWAPCHAIN_USAGE_COLOR_ATTACHMENT_BIT |
                           XR_SWAPCHAIN_USAGE_SAMPLED_BIT;
        info.format      = chosen;
        info.sampleCount = 1;
        info.width       = (uint32_t) e->w;
        info.height      = (uint32_t) e->h;
        info.faceCount   = 1;
        info.arraySize   = 1;
        info.mipCount    = 1;

        XR_TRY(xrCreateSwapchain(xr_session, &info, &e->handle));

        XR_TRY(xrEnumerateSwapchainImages(e->handle, 0, &e->image_count, NULL));

        e->images = calloc(e->image_count, sizeof (*e->images));
        e->fbos   = calloc(e->image_count, sizeof (*e->fbos));

        if (!e->images || !e->fbos) return 0;

        for (j = 0; j < e->image_count; j++)
            e->images[j].type = XR_TYPE_SWAPCHAIN_IMAGE_OPENGL_ES_KHR;

        XR_TRY(xrEnumerateSwapchainImages(
                   e->handle, e->image_count, &e->image_count,
                   (XrSwapchainImageBaseHeader *) e->images));

        /* One depth+stencil buffer per eye, shared across its images: we
         * render the eye's images strictly in sequence. The stencil matters
         * -- ball/game_draw.c:520-556 needs it for reflections. */

        glGenRenderbuffers(1, &e->depth);
        glBindRenderbuffer(GL_RENDERBUFFER, e->depth);
        glRenderbufferStorage(GL_RENDERBUFFER, GL_DEPTH24_STENCIL8, e->w, e->h);
        glBindRenderbuffer(GL_RENDERBUFFER, 0);

        glGenFramebuffers(e->image_count, e->fbos);

        for (j = 0; j < e->image_count; j++)
        {
            GLenum status;

            glBindFramebuffer(GL_FRAMEBUFFER, e->fbos[j]);
            glFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0,
                                   GL_TEXTURE_2D, e->images[j].image, 0);
            glFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_DEPTH_ATTACHMENT,
                                      GL_RENDERBUFFER, e->depth);
            glFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_STENCIL_ATTACHMENT,
                                      GL_RENDERBUFFER, e->depth);

            status = glCheckFramebufferStatus(GL_FRAMEBUFFER);

            if (status != GL_FRAMEBUFFER_COMPLETE)
            {
                loge("eye %u image %u: framebuffer incomplete (0x%x)",
                     i, j, (unsigned) status);
                return 0;
            }
        }

        glBindFramebuffer(GL_FRAMEBUFFER, 0);

        logi("eye %u: %dx%d, %u images", i, e->w, e->h, e->image_count);
    }

    for (i = 0; i < EYE_COUNT; i++)
        xr_views[i].type = XR_TYPE_VIEW;

    return 1;
}

/*---------------------------------------------------------------------------*/
/* Input                                                                     */

static int xr_init_actions(void)
{
    XrActionSetCreateInfo set_info;
    XrActionCreateInfo    act_info;
    XrActionSpaceCreateInfo space_info;
    XrSessionActionSetsAttachInfo attach;
    XrInteractionProfileSuggestedBinding suggest;

    XrPath profile;
    XrPath p_tilt, p_select_l, p_select_r, p_grip_r;

    XrActionSuggestedBinding bindings[4];

    memset(&set_info, 0, sizeof (set_info));
    set_info.type = XR_TYPE_ACTION_SET_CREATE_INFO;
    strcpy(set_info.actionSetName,          "gameplay");
    strcpy(set_info.localizedActionSetName, "Gameplay");

    XR_TRY(xrCreateActionSet(xr_instance, &set_info, &xr_actions));

    memset(&act_info, 0, sizeof (act_info));
    act_info.type      = XR_TYPE_ACTION_CREATE_INFO;
    act_info.actionType = XR_ACTION_TYPE_VECTOR2F_INPUT;
    strcpy(act_info.actionName,          "tilt");
    strcpy(act_info.localizedActionName, "Tilt");
    XR_TRY(xrCreateAction(xr_actions, &act_info, &act_tilt));

    act_info.actionType = XR_ACTION_TYPE_BOOLEAN_INPUT;
    strcpy(act_info.actionName,          "select");
    strcpy(act_info.localizedActionName, "Select");
    XR_TRY(xrCreateAction(xr_actions, &act_info, &act_select));

    act_info.actionType = XR_ACTION_TYPE_POSE_INPUT;
    strcpy(act_info.actionName,          "grip_pose");
    strcpy(act_info.localizedActionName, "Grip pose");
    XR_TRY(xrCreateAction(xr_actions, &act_info, &act_grip_pose));

    XR_TRY(xrStringToPath(xr_instance,
                          "/interaction_profiles/oculus/touch_controller",
                          &profile));

    XR_TRY(xrStringToPath(xr_instance, "/user/hand/left/input/thumbstick",  &p_tilt));
    XR_TRY(xrStringToPath(xr_instance, "/user/hand/left/input/trigger/value",  &p_select_l));
    XR_TRY(xrStringToPath(xr_instance, "/user/hand/right/input/trigger/value", &p_select_r));
    XR_TRY(xrStringToPath(xr_instance, "/user/hand/right/input/grip/pose", &p_grip_r));

    bindings[0].action = act_tilt;      bindings[0].binding = p_tilt;
    bindings[1].action = act_select;    bindings[1].binding = p_select_l;
    bindings[2].action = act_select;    bindings[2].binding = p_select_r;
    bindings[3].action = act_grip_pose; bindings[3].binding = p_grip_r;

    memset(&suggest, 0, sizeof (suggest));
    suggest.type = XR_TYPE_INTERACTION_PROFILE_SUGGESTED_BINDING;
    suggest.interactionProfile     = profile;
    suggest.countSuggestedBindings = 4;
    suggest.suggestedBindings      = bindings;

    XR_TRY(xrSuggestInteractionProfileBindings(xr_instance, &suggest));

    memset(&space_info, 0, sizeof (space_info));
    space_info.type   = XR_TYPE_ACTION_SPACE_CREATE_INFO;
    space_info.action = act_grip_pose;
    space_info.poseInActionSpace.orientation.w = 1.0f;

    XR_TRY(xrCreateActionSpace(xr_session, &space_info, &xr_grip_space));

    memset(&attach, 0, sizeof (attach));
    attach.type = XR_TYPE_SESSION_ACTION_SETS_ATTACH_INFO;
    attach.countActionSets = 1;
    attach.actionSets      = &xr_actions;

    XR_TRY(xrAttachSessionActionSets(xr_session, &attach));

    logi("action set attached");

    return 1;
}

static void xr_poll_input(void)
{
    XrActiveActionSet active;
    XrActionsSyncInfo sync;
    XrActionStateVector2f tilt;
    XrActionStateBoolean  select;
    XrSpaceLocation       grip;

    XrActionStateGetInfo get;

    static int last_select = -1;
    static int log_throttle;

    memset(&active, 0, sizeof (active));
    active.actionSet     = xr_actions;
    active.subactionPath = XR_NULL_PATH;

    memset(&sync, 0, sizeof (sync));
    sync.type = XR_TYPE_ACTIONS_SYNC_INFO;
    sync.countActiveActionSets = 1;
    sync.activeActionSets      = &active;

    if (XR_FAILED(xrSyncActions(xr_session, &sync)))
        return;

    memset(&get, 0, sizeof (get));
    get.type = XR_TYPE_ACTION_STATE_GET_INFO;

    memset(&tilt, 0, sizeof (tilt));
    tilt.type = XR_TYPE_ACTION_STATE_VECTOR2F;
    get.action = act_tilt;
    xrGetActionStateVector2f(xr_session, &get, &tilt);

    memset(&select, 0, sizeof (select));
    select.type = XR_TYPE_ACTION_STATE_BOOLEAN;
    get.action = act_select;
    xrGetActionStateBoolean(xr_session, &get, &select);

    memset(&grip, 0, sizeof (grip));
    grip.type = XR_TYPE_SPACE_LOCATION;
    xrLocateSpace(xr_grip_space, xr_space, xr_display_time, &grip);

    if (select.isActive && (int) select.currentState != last_select)
    {
        last_select = (int) select.currentState;
        logi("select = %d", last_select);
    }

    /* Roughly once a second at 72 Hz. */

    if (++log_throttle >= 72)
    {
        log_throttle = 0;

        logi("tilt = (%+.2f, %+.2f) active=%d | grip = (%+.2f %+.2f %+.2f) flags=0x%x",
             tilt.currentState.x, tilt.currentState.y, (int) tilt.isActive,
             grip.pose.position.x, grip.pose.position.y, grip.pose.position.z,
             (unsigned) grip.locationFlags);
    }
}

/*---------------------------------------------------------------------------*/
/* Session state machine                                                     */

static int xr_poll_events(void)
{
    XrEventDataBuffer ev;

    for (;;)
    {
        memset(&ev, 0, sizeof (ev));
        ev.type = XR_TYPE_EVENT_DATA_BUFFER;

        if (xrPollEvent(xr_instance, &ev) != XR_SUCCESS)
            break;

        switch (ev.type)
        {
        case XR_TYPE_EVENT_DATA_SESSION_STATE_CHANGED:
        {
            const XrEventDataSessionStateChanged *e =
                (const XrEventDataSessionStateChanged *) &ev;

            xr_state = e->state;

            logi("session state -> %d", (int) xr_state);

            if (xr_state == XR_SESSION_STATE_READY)
            {
                XrSessionBeginInfo begin;

                memset(&begin, 0, sizeof (begin));
                begin.type = XR_TYPE_SESSION_BEGIN_INFO;
                begin.primaryViewConfigurationType =
                    XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO;

                if (XR_SUCCEEDED(xrBeginSession(xr_session, &begin)))
                {
                    xr_running = 1;
                    logi("session begun");
                }
            }
            else if (xr_state == XR_SESSION_STATE_STOPPING)
            {
                xr_running = 0;
                xrEndSession(xr_session);
                logi("session ended");
            }
            else if (xr_state == XR_SESSION_STATE_EXITING ||
                     xr_state == XR_SESSION_STATE_LOSS_PENDING)
            {
                return 0;
            }
            break;
        }

        case XR_TYPE_EVENT_DATA_INSTANCE_LOSS_PENDING:
            logi("instance loss pending");
            return 0;

        case XR_TYPE_EVENT_DATA_INTERACTION_PROFILE_CHANGED:
            logi("interaction profile changed");
            break;

        case XR_TYPE_EVENT_DATA_REFERENCE_SPACE_CHANGE_PENDING:
            logi("reference space change pending (recentre)");
            break;

        default:
            break;
        }
    }

    return 1;
}

/*---------------------------------------------------------------------------*/
/* Frame                                                                     */

/*
 * These three mirror hmd_prep_left/hmd_prep_right/hmd_swap so that the
 * swapchain acquire/release ordering the port depends on is exercised here.
 * share/state.c:167-180 guarantees strict left -> right -> swap, so the left
 * image is released when the right one is acquired, and the right one in
 * swap. There is no other hook in share/hmd.h to do it in.
 */

static int   eye_acquired = -1;
static uint32_t eye_index;

static void prep_eye(int eye)
{
    struct eye_swapchain *e;

    XrSwapchainImageAcquireInfo acq;
    XrSwapchainImageWaitInfo    wait;

    if (eye_acquired >= 0)
    {
        XrSwapchainImageReleaseInfo rel;
        memset(&rel, 0, sizeof (rel));
        rel.type = XR_TYPE_SWAPCHAIN_IMAGE_RELEASE_INFO;
        xrReleaseSwapchainImage(xr_eye[eye_acquired].handle, &rel);
        eye_acquired = -1;
    }

    e = &xr_eye[eye];

    memset(&acq, 0, sizeof (acq));
    acq.type = XR_TYPE_SWAPCHAIN_IMAGE_ACQUIRE_INFO;

    if (XR_FAILED(xrAcquireSwapchainImage(e->handle, &acq, &eye_index)))
        return;

    memset(&wait, 0, sizeof (wait));
    wait.type    = XR_TYPE_SWAPCHAIN_IMAGE_WAIT_INFO;
    wait.timeout = XR_INFINITE_DURATION;

    if (XR_FAILED(xrWaitSwapchainImage(e->handle, &wait)))
        return;

    eye_acquired = eye;

    glBindFramebuffer(GL_FRAMEBUFFER, e->fbos[eye_index]);
    glViewport(0, 0, e->w, e->h);
    glScissor(0, 0, e->w, e->h);
}

static void release_eye(void)
{
    if (eye_acquired >= 0)
    {
        XrSwapchainImageReleaseInfo rel;
        memset(&rel, 0, sizeof (rel));
        rel.type = XR_TYPE_SWAPCHAIN_IMAGE_RELEASE_INFO;
        xrReleaseSwapchainImage(xr_eye[eye_acquired].handle, &rel);
        eye_acquired = -1;
    }
}

static void render_eye(int eye, float t)
{
    float P[16], V[16];

    m_projection(P, &xr_views[eye].fov, 0.05f, 100.0f);
    m_view_from_pose(V, &xr_views[eye].pose);

    glMatrixMode(GL_PROJECTION);
    glLoadMatrixf(P);

    glMatrixMode(GL_MODELVIEW);
    glLoadMatrixf(V);

    glClearColor(0.05f, 0.06f, 0.09f, 1.0f);
    glClearStencil(0);
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT | GL_STENCIL_BUFFER_BIT);

    draw_scene(t);
}

static void xr_frame(float t)
{
    XrFrameWaitInfo   wait;
    XrFrameState      state;
    XrFrameBeginInfo  begin;
    XrFrameEndInfo    end;

    XrViewLocateInfo  locate;
    XrViewState       view_state;
    uint32_t          view_count = EYE_COUNT;

    XrCompositionLayerProjectionView views[EYE_COUNT];
    XrCompositionLayerProjection     layer;
    const XrCompositionLayerBaseHeader *layers[1];

    int i;

    memset(&wait, 0, sizeof (wait));
    wait.type = XR_TYPE_FRAME_WAIT_INFO;

    memset(&state, 0, sizeof (state));
    state.type = XR_TYPE_FRAME_STATE;

    if (XR_FAILED(xrWaitFrame(xr_session, &wait, &state)))
        return;

    xr_display_time  = state.predictedDisplayTime;
    xr_should_render = state.shouldRender;

    memset(&begin, 0, sizeof (begin));
    begin.type = XR_TYPE_FRAME_BEGIN_INFO;

    if (XR_FAILED(xrBeginFrame(xr_session, &begin)))
        return;

    memset(&view_state, 0, sizeof (view_state));
    view_state.type = XR_TYPE_VIEW_STATE;

    memset(&locate, 0, sizeof (locate));
    locate.type                  = XR_TYPE_VIEW_LOCATE_INFO;
    locate.viewConfigurationType = XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO;
    locate.displayTime           = xr_display_time;
    locate.space                 = xr_space;

    xrLocateViews(xr_session, &locate, &view_state, EYE_COUNT,
                  &view_count, xr_views);

    xr_poll_input();

    memset(&end, 0, sizeof (end));
    end.type                 = XR_TYPE_FRAME_END_INFO;
    end.displayTime          = xr_display_time;
    end.environmentBlendMode = XR_ENVIRONMENT_BLEND_MODE_OPAQUE;

    if (!xr_should_render ||
        !(view_state.viewStateFlags & XR_VIEW_STATE_POSITION_VALID_BIT))
    {
        /* Still must end the frame, just with nothing in it. */

        end.layerCount = 0;
        end.layers     = NULL;
        xrEndFrame(xr_session, &end);
        return;
    }

    for (i = 0; i < EYE_COUNT; i++)
    {
        prep_eye(i);
        render_eye(i, t);

        memset(&views[i], 0, sizeof (views[i]));
        views[i].type = XR_TYPE_COMPOSITION_LAYER_PROJECTION_VIEW;
        views[i].pose = xr_views[i].pose;
        views[i].fov  = xr_views[i].fov;
        views[i].subImage.swapchain               = xr_eye[i].handle;
        views[i].subImage.imageRect.offset.x      = 0;
        views[i].subImage.imageRect.offset.y      = 0;
        views[i].subImage.imageRect.extent.width  = xr_eye[i].w;
        views[i].subImage.imageRect.extent.height = xr_eye[i].h;
        views[i].subImage.imageArrayIndex         = 0;
    }

    release_eye();

    glBindFramebuffer(GL_FRAMEBUFFER, 0);

    memset(&layer, 0, sizeof (layer));
    layer.type       = XR_TYPE_COMPOSITION_LAYER_PROJECTION;
    layer.space      = xr_space;
    layer.viewCount  = EYE_COUNT;
    layer.views      = views;

    layers[0] = (const XrCompositionLayerBaseHeader *) &layer;

    end.layerCount = 1;
    end.layers     = layers;

    xrEndFrame(xr_session, &end);
}


/*---------------------------------------------------------------------------*/
/* Automated GL conformance self-test                                        */

/*
 * The two features most likely to break under GL-to-GLES translation are the
 * GL_COMBINE texenv chain and the stencil reflection pass. Judging those by
 * eye through a headset is unreliable, so render each into a small offscreen
 * buffer with analytically known inputs and read the pixels back. Results go
 * to logcat as PASS/FAIL with actual-versus-expected values.
 */

#define ST_SIZE 64

static GLuint st_fbo, st_tex, st_rb;
static int    st_failures;

static GLuint make_tex_1x1(unsigned char r, unsigned char g,
                           unsigned char b, unsigned char a)
{
    const unsigned char px[4] = { r, g, b, a };
    GLuint t = 0;

    glGenTextures(1, &t);
    glBindTexture(GL_TEXTURE_2D, t);
    glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, 1, 1, 0,
                 GL_RGBA, GL_UNSIGNED_BYTE, px);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST);

    return t;
}

static void st_quad(float x0, float y0, float x1, float y1)
{
    const GLfloat v[8] = { x0, y0,  x1, y0,  x0, y1,  x1, y1 };
    const GLfloat t[8] = { 0, 0,  1, 0,  0, 1,  1, 1 };

    glEnableClientState(GL_VERTEX_ARRAY);
    glVertexPointer(2, GL_FLOAT, 0, v);

    glClientActiveTexture(GL_TEXTURE0);
    glEnableClientState(GL_TEXTURE_COORD_ARRAY);
    glTexCoordPointer(2, GL_FLOAT, 0, t);

    glClientActiveTexture(GL_TEXTURE1);
    glEnableClientState(GL_TEXTURE_COORD_ARRAY);
    glTexCoordPointer(2, GL_FLOAT, 0, t);
    glClientActiveTexture(GL_TEXTURE0);

    glDrawArrays(GL_TRIANGLE_STRIP, 0, 4);

    glClientActiveTexture(GL_TEXTURE1);
    glDisableClientState(GL_TEXTURE_COORD_ARRAY);
    glClientActiveTexture(GL_TEXTURE0);
    glDisableClientState(GL_TEXTURE_COORD_ARRAY);
    glDisableClientState(GL_VERTEX_ARRAY);
}

static void st_read(int x, int y, unsigned char *px)
{
    glReadPixels(x, y, 1, 1, GL_RGBA, GL_UNSIGNED_BYTE, px);
}

static void st_check(const char *name, const unsigned char *got,
                     int er, int eg, int eb, int tol)
{
    const int ok = (abs((int) got[0] - er) <= tol &&
                    abs((int) got[1] - eg) <= tol &&
                    abs((int) got[2] - eb) <= tol);

    if (ok)
        logi("SELFTEST %-22s PASS  got (%3d,%3d,%3d)",
             name, got[0], got[1], got[2]);
    else
    {
        loge("SELFTEST %-22s FAIL  got (%3d,%3d,%3d) expected (%3d,%3d,%3d)",
             name, got[0], got[1], got[2], er, eg, eb);
        st_failures++;
    }
}

static void st_begin(void)
{
    glBindFramebuffer(GL_FRAMEBUFFER, st_fbo);
    glViewport(0, 0, ST_SIZE, ST_SIZE);

    glMatrixMode(GL_PROJECTION);
    glLoadIdentity();
    glOrtho(0.0, 1.0, 0.0, 1.0, -1.0, 1.0);

    glMatrixMode(GL_MODELVIEW);
    glLoadIdentity();

    glDisable(GL_DEPTH_TEST);
    glDisable(GL_LIGHTING);
    glDisable(GL_CULL_FACE);
    glDisable(GL_BLEND);
}

/*
 * Two-unit GL_COMBINE chain of the same shape as share/geom.c:104-207.
 *
 *   unit 0: MODULATE(PRIMARY_COLOR, ONE_MINUS_SRC_ALPHA(TEXTURE))
 *           = 1.0 * (1 - 0.5) = 0.5
 *   unit 1: INTERPOLATE(PREVIOUS, TEXTURE, TEXTURE.alpha)
 *           = prev*a + tex*(1-a), a = 0.25
 *           R = 0.5*0.25 + 0.00*0.75 = 0.125 -> 32
 *           G = 0.5*0.25 + 1.00*0.75 = 0.875 -> 223
 *           B = 0.5*0.25 + 0.00*0.75 = 0.125 -> 32
 */

static void st_test_combine(void)
{
    GLuint a = make_tex_1x1(255,   0,   0, 128);
    GLuint b = make_tex_1x1(  0, 255,   0,  64);

    unsigned char px[4];

    glClearColor(0.0f, 0.0f, 0.0f, 1.0f);
    glClear(GL_COLOR_BUFFER_BIT);

    glColor4f(1.0f, 1.0f, 1.0f, 1.0f);

    glActiveTexture(GL_TEXTURE0);
    glEnable(GL_TEXTURE_2D);
    glBindTexture(GL_TEXTURE_2D, a);
    glTexEnvi(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_COMBINE);
    glTexEnvi(GL_TEXTURE_ENV, GL_COMBINE_RGB,  GL_MODULATE);
    glTexEnvi(GL_TEXTURE_ENV, GL_SRC0_RGB,     GL_PRIMARY_COLOR);
    glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND0_RGB, GL_SRC_COLOR);
    glTexEnvi(GL_TEXTURE_ENV, GL_SRC1_RGB,     GL_TEXTURE);
    glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND1_RGB, GL_ONE_MINUS_SRC_ALPHA);

    glActiveTexture(GL_TEXTURE1);
    glEnable(GL_TEXTURE_2D);
    glBindTexture(GL_TEXTURE_2D, b);
    glTexEnvi(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_COMBINE);
    glTexEnvi(GL_TEXTURE_ENV, GL_COMBINE_RGB,  GL_INTERPOLATE);
    glTexEnvi(GL_TEXTURE_ENV, GL_SRC0_RGB,     GL_PREVIOUS);
    glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND0_RGB, GL_SRC_COLOR);
    glTexEnvi(GL_TEXTURE_ENV, GL_SRC1_RGB,     GL_TEXTURE);
    glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND1_RGB, GL_SRC_COLOR);
    glTexEnvi(GL_TEXTURE_ENV, GL_SRC2_RGB,     GL_TEXTURE);
    glTexEnvi(GL_TEXTURE_ENV, GL_OPERAND2_RGB, GL_SRC_ALPHA);

    st_quad(0.0f, 0.0f, 1.0f, 1.0f);

    st_read(ST_SIZE / 2, ST_SIZE / 2, px);
    st_check("texenv_combine", px, 32, 223, 32, 10);

    glActiveTexture(GL_TEXTURE1);
    glTexEnvi(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_MODULATE);
    glDisable(GL_TEXTURE_2D);
    glActiveTexture(GL_TEXTURE0);
    glTexEnvi(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_MODULATE);
    glDisable(GL_TEXTURE_2D);

    glDeleteTextures(1, &a);
    glDeleteTextures(1, &b);
}

/*
 * Stencil mask then a masked draw, the shape ball/game_draw.c:520-556 uses
 * for reflections. Left half should end up blue, right half black.
 */

static void st_test_stencil(void)
{
    unsigned char l[4], r[4];

    glClearColor(0.0f, 0.0f, 0.0f, 1.0f);
    glClearStencil(0);
    glClear(GL_COLOR_BUFFER_BIT | GL_STENCIL_BUFFER_BIT);

    glEnable(GL_STENCIL_TEST);

    glStencilFunc(GL_ALWAYS, 1, 0xFFFFFFFF);
    glStencilOp(GL_REPLACE, GL_REPLACE, GL_REPLACE);
    glColorMask(GL_FALSE, GL_FALSE, GL_FALSE, GL_FALSE);
    glColor4f(1.0f, 1.0f, 1.0f, 1.0f);
    st_quad(0.0f, 0.0f, 0.5f, 1.0f);
    glColorMask(GL_TRUE, GL_TRUE, GL_TRUE, GL_TRUE);

    glStencilOp(GL_KEEP, GL_KEEP, GL_KEEP);
    glStencilFunc(GL_EQUAL, 1, 0xFFFFFFFF);
    glColor4f(0.0f, 0.0f, 1.0f, 1.0f);
    st_quad(0.0f, 0.0f, 1.0f, 1.0f);

    glDisable(GL_STENCIL_TEST);
    glColor4f(1.0f, 1.0f, 1.0f, 1.0f);

    st_read(ST_SIZE / 4,     ST_SIZE / 2, l);
    st_read(3 * ST_SIZE / 4, ST_SIZE / 2, r);

    st_check("stencil_inside",  l, 0, 0, 255, 4);
    st_check("stencil_outside", r, 0, 0,   0, 4);
}

/*
 * The GL_TEXTURE matrix stack, which share/solid_draw.c:78-125 uses to
 * project the ball shadow. Shifting texture coordinates by half a texel
 * width must select the other half of a 2x1 texture.
 */

static void st_test_texmatrix(void)
{
    const unsigned char texels[8] = { 255, 0, 0, 255,    0, 0, 255, 255 };

    GLuint t = 0;
    unsigned char a[4], b[4];

    glGenTextures(1, &t);
    glBindTexture(GL_TEXTURE_2D, t);
    glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, 2, 1, 0,
                 GL_RGBA, GL_UNSIGNED_BYTE, texels);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);

    glActiveTexture(GL_TEXTURE0);
    glEnable(GL_TEXTURE_2D);
    glTexEnvi(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_REPLACE);

    /* Identity texture matrix: the left texel (red) is sampled at s=0.25. */

    glMatrixMode(GL_TEXTURE);
    glLoadIdentity();
    glMatrixMode(GL_MODELVIEW);

    glClear(GL_COLOR_BUFFER_BIT);
    st_quad(0.0f, 0.0f, 0.5f, 1.0f);
    st_read(ST_SIZE / 8, ST_SIZE / 2, a);

    /* Shift s by +0.5: the right texel (blue) should be sampled instead. */

    glMatrixMode(GL_TEXTURE);
    glLoadIdentity();
    glTranslatef(0.5f, 0.0f, 0.0f);
    glMatrixMode(GL_MODELVIEW);

    glClear(GL_COLOR_BUFFER_BIT);
    st_quad(0.0f, 0.0f, 0.5f, 1.0f);
    st_read(ST_SIZE / 8, ST_SIZE / 2, b);

    glMatrixMode(GL_TEXTURE);
    glLoadIdentity();
    glMatrixMode(GL_MODELVIEW);

    st_check("texmatrix_identity", a, 255, 0,   0, 8);
    st_check("texmatrix_shifted",  b,   0, 0, 255, 8);

    glTexEnvi(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_MODULATE);
    glDisable(GL_TEXTURE_2D);
    glDeleteTextures(1, &t);
}

static void selftest_run(void)
{
    GLenum status;

    glGenTextures(1, &st_tex);
    glBindTexture(GL_TEXTURE_2D, st_tex);
    glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, ST_SIZE, ST_SIZE, 0,
                 GL_RGBA, GL_UNSIGNED_BYTE, NULL);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST);

    glGenRenderbuffers(1, &st_rb);
    glBindRenderbuffer(GL_RENDERBUFFER, st_rb);
    glRenderbufferStorage(GL_RENDERBUFFER, GL_DEPTH24_STENCIL8, ST_SIZE, ST_SIZE);
    glBindRenderbuffer(GL_RENDERBUFFER, 0);

    glGenFramebuffers(1, &st_fbo);
    glBindFramebuffer(GL_FRAMEBUFFER, st_fbo);
    glFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0,
                           GL_TEXTURE_2D, st_tex, 0);
    glFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_DEPTH_ATTACHMENT,
                              GL_RENDERBUFFER, st_rb);
    glFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_STENCIL_ATTACHMENT,
                              GL_RENDERBUFFER, st_rb);

    status = glCheckFramebufferStatus(GL_FRAMEBUFFER);

    if (status != GL_FRAMEBUFFER_COMPLETE)
    {
        loge("SELFTEST framebuffer incomplete (0x%x) -- skipping",
             (unsigned) status);
        glBindFramebuffer(GL_FRAMEBUFFER, 0);
        return;
    }

    while (glGetError() != GL_NO_ERROR)
        ;

    st_begin();

    st_test_combine();
    st_test_stencil();
    st_test_texmatrix();

    {
        const GLenum err = glGetError();

        if (err != GL_NO_ERROR)
            loge("SELFTEST left GL error 0x%x", (unsigned) err);
    }

    glBindFramebuffer(GL_FRAMEBUFFER, 0);

    glDeleteFramebuffers(1, &st_fbo);
    glDeleteRenderbuffers(1, &st_rb);
    glDeleteTextures(1, &st_tex);

    if (st_failures)
        loge("SELFTEST %d of 5 checks FAILED", st_failures);
    else
        logi("SELFTEST all checks passed");
}

/*---------------------------------------------------------------------------*/

int main(int argc, char *argv[])
{
    Uint32 start, last_report;
    int    frames = 0;
    int    done   = 0;

    (void) argc;
    (void) argv;

    logi("--- Neverball Quest spike (M0) ---");

    if (!init_sdl_gl())    { loge("GL setup failed");      return 1; }
    if (!xr_init_loader()) { loge("loader init failed");   return 1; }
    if (!xr_init_instance()){ loge("instance init failed"); return 1; }
    if (!xr_init_session()) { loge("session init failed");  return 1; }
    if (!xr_init_swapchains()) { loge("swapchain init failed"); return 1; }
    if (!xr_init_actions()) { loge("action init failed");   return 1; }

    tex_checker  = make_checker(64, 8);
    tex_gradient = make_gradient(64);
    make_quad_vbo();

    selftest_run();

    logi("--- init complete, entering frame loop ---");

    start = last_report = SDL_GetTicks();

    while (!done)
    {
        SDL_Event e;

        while (SDL_PollEvent(&e))
        {
            switch (e.type)
            {
            case SDL_QUIT:
                done = 1;
                break;

            /* Android lifecycle, absent from ball/main.c today. */

            case SDL_APP_WILLENTERBACKGROUND:
                logi("SDL_APP_WILLENTERBACKGROUND");
                break;
            case SDL_APP_DIDENTERFOREGROUND:
                logi("SDL_APP_DIDENTERFOREGROUND");
                break;
            case SDL_APP_TERMINATING:
                logi("SDL_APP_TERMINATING");
                done = 1;
                break;

            default:
                break;
            }
        }

        if (!xr_poll_events())
            break;

        if (xr_running)
        {
            xr_frame((float) (SDL_GetTicks() - start) * 0.001f);
            frames++;
        }
        else
            SDL_Delay(20);

        {
            const Uint32 now = SDL_GetTicks();

            if (now - last_report >= 5000)
            {
                logi("%.1f fps (%d frames in %u ms), GL error 0x%x",
                     1000.0f * frames / (float) (now - last_report),
                     frames, (unsigned) (now - last_report),
                     (unsigned) glGetError());

                frames = 0;
                last_report = now;
            }
        }
    }

    logi("--- shutting down ---");

    if (xr_session)  xrDestroySession(xr_session);
    if (xr_instance) xrDestroyInstance(xr_instance);

    SDL_GL_DeleteContext(gl_context);
    SDL_DestroyWindow(window);
    SDL_Quit();

    return 0;
}

/*---------------------------------------------------------------------------*/
