/* Generated by Claude Code 2.1.263 (claude-opus-5[1m]) */

package org.neverputt;

import org.libsdl.app.SDLActivity;

/**
 * Neverputt's Android entry point.
 *
 * Identical in shape to Neverball's: SDL supplies the Android lifecycle, JNI
 * environment and audio, OpenXR owns the display, and SDL's own window is
 * created but never presented to. The two ship as separate APKs because the
 * Horizon launcher lists applications, not the games inside them.
 */
public class NeverputtActivity extends SDLActivity
{
    @Override
    protected String[] getLibraries()
    {
        /* The last entry is also the library SDL looks up SDL_main in. */

        return new String[] { "SDL2", "neverputt" };
    }
}
