/* Generated by Claude Code 2.1.263 (claude-opus-5[1m]) */

/*
 * Copyright (C) 2026 Neverball authors
 *
 * NEVERBALL is  free software; you can redistribute  it and/or modify
 * it under the  terms of the GNU General  Public License as published
 * by the Free  Software Foundation; either version 2  of the License,
 * or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT  ANY  WARRANTY;  without   even  the  implied  warranty  of
 * MERCHANTABILITY or  FITNESS FOR A PARTICULAR PURPOSE.   See the GNU
 * General Public License for more details.
 */

/*
 * Game data lives as ZIP archives inside the APK. They are stored
 * uncompressed (see the noCompress setting in android/app/build.gradle), so
 * the asset manager can map them and hand back a pointer, and miniz can read
 * them in place. That avoids extracting 150 MB to internal storage on first
 * run and keeps the on-device footprint to a single copy.
 */

#include <stdlib.h>
#include <string.h>

#include <SDL.h>
#include <SDL_system.h>

#include <android/asset_manager.h>
#include <android/asset_manager_jni.h>
#include <jni.h>

#include "fs.h"
#include "common.h"
#include "log.h"

/*---------------------------------------------------------------------------*/

/*
 * Mounted assets are held open for the process lifetime: miniz reads
 * directly out of the mapping, so it must not be released.
 */

#define ASSET_MAX 32

static AAsset *assets[ASSET_MAX];
static int     asset_count;

static AAssetManager *asset_manager(void)
{
    static AAssetManager *manager;

    JNIEnv  *env;
    jobject  activity;
    jclass   cls;
    jmethodID mid;
    jobject  jassets;

    if (manager)
        return manager;

    if (!(env = (JNIEnv *) SDL_AndroidGetJNIEnv()))
    {
        log_printf("FS: no JNI environment\n");
        return NULL;
    }

    if (!(activity = (jobject) SDL_AndroidGetActivity()))
    {
        log_printf("FS: no activity\n");
        return NULL;
    }

    cls = (*env)->GetObjectClass(env, activity);
    mid = (*env)->GetMethodID(env, cls, "getAssets",
                              "()Landroid/content/res/AssetManager;");

    if (!mid)
    {
        log_printf("FS: no getAssets method\n");
        (*env)->DeleteLocalRef(env, activity);
        return NULL;
    }

    jassets = (*env)->CallObjectMethod(env, activity, mid);

    /* The manager outlives this frame, so the reference must too. */

    jassets = (*env)->NewGlobalRef(env, jassets);
    manager = AAssetManager_fromJava(env, jassets);

    (*env)->DeleteLocalRef(env, cls);
    (*env)->DeleteLocalRef(env, activity);

    return manager;
}

static int cmp_name(const void *a, const void *b)
{
    return strcmp(*(const char **) a, *(const char **) b);
}

static int mount_asset(AAssetManager *manager, const char *name)
{
    AAsset *asset;
    const void *data;
    off_t size;

    if (asset_count >= ASSET_MAX)
    {
        log_printf("FS: too many assets to mount\n");
        return 0;
    }

    if (!(asset = AAssetManager_open(manager, name, AASSET_MODE_BUFFER)))
    {
        log_printf("FS: cannot open asset \"%s\"\n", name);
        return 0;
    }

    size = AAsset_getLength(asset);
    data = AAsset_getBuffer(asset);

    if (!data)
    {
        /*
         * Only stored (uncompressed) assets can be mapped. If the packaging
         * ever changes, fail loudly rather than silently losing the data.
         */

        log_printf("FS: asset \"%s\" is not mappable; is it compressed?\n",
                   name);
        AAsset_close(asset);
        return 0;
    }

    if (!fs_add_path_mem(name, data, (size_t) size))
    {
        AAsset_close(asset);
        return 0;
    }

    assets[asset_count++] = asset;

    return 1;
}

int fs_add_apk_assets(void)
{
    AAssetManager *manager;
    AAssetDir *dir;

    char *names[ASSET_MAX];
    int   count = 0, i, mounted = 0;

    const char *name;

    if (!(manager = asset_manager()))
        return 0;

    if (!(dir = AAssetManager_openDir(manager, "")))
    {
        log_printf("FS: cannot open asset directory\n");
        return 0;
    }

    while ((name = AAssetDir_getNextFileName(dir)) && count < ASSET_MAX)
        if (str_ends_with(name, ".zip"))
            names[count++] = strdup(name);

    AAssetDir_close(dir);

    /*
     * Archives further down the alphabet take precedence, matching the
     * ordering config_paths() documents for on-disk search paths.
     */

    qsort(names, count, sizeof (*names), cmp_name);

    for (i = 0; i < count; i++)
    {
        mounted += mount_asset(manager, names[i]);
        free(names[i]);
    }

    log_printf("FS: mounted %d of %d asset archives\n", mounted, count);

    return mounted;
}

/*---------------------------------------------------------------------------*/
