/* Generated by Claude Code 2.1.263 (claude-opus-5[1m]) */

#include <string.h>

#include "hmd_math.h"

/*---------------------------------------------------------------------------*/

void hmd_frustum(float *M, const float t[4], float n, float f)
{
    const float w = t[1] - t[0];
    const float h = t[3] - t[2];

    memset(M, 0, 16 * sizeof (float));

    M[0]  = 2.0f / w;
    M[5]  = 2.0f / h;
    M[8]  = (t[1] + t[0]) / w;
    M[9]  = (t[3] + t[2]) / h;
    M[10] = -(f + n) / (f - n);
    M[11] = -1.0f;
    M[14] = -(2.0f * f * n) / (f - n);
}

void hmd_view(float *M, const float q[4], const float p[3])
{
    const float x = q[0];
    const float y = q[1];
    const float z = q[2];
    const float w = q[3];

    /* The rotation of the pose, transposed in place: transposing a rotation
     * inverts it, which is half of inverting the pose. */

    M[0]  = 1.0f - 2.0f * (y * y + z * z);
    M[4]  =        2.0f * (x * y + z * w);
    M[8]  =        2.0f * (x * z - y * w);
    M[12] = 0.0f;

    M[1]  =        2.0f * (x * y - z * w);
    M[5]  = 1.0f - 2.0f * (x * x + z * z);
    M[9]  =        2.0f * (y * z + x * w);
    M[13] = 0.0f;

    M[2]  =        2.0f * (x * z + y * w);
    M[6]  =        2.0f * (y * z - x * w);
    M[10] = 1.0f - 2.0f * (x * x + y * y);
    M[14] = 0.0f;

    M[3]  = 0.0f;
    M[7]  = 0.0f;
    M[11] = 0.0f;
    M[15] = 1.0f;

    /* And the other half: the transposed rotation applied to -p. */

    M[12] = -(M[0] * p[0] + M[4] * p[1] + M[8]  * p[2]);
    M[13] = -(M[1] * p[0] + M[5] * p[1] + M[9]  * p[2]);
    M[14] = -(M[2] * p[0] + M[6] * p[1] + M[10] * p[2]);
}

/*---------------------------------------------------------------------------*/
