/* Generated by Claude Code 2.1.263 (claude-opus-5[1m]) */

/*
 * OpenXR backend for the HMD abstraction of share/hmd.h.
 *
 * Unlike share/hmd_openhmd.c this does not use share/hmd_common.c: the
 * barrel and chromatic distortion it applies is the compositor's job on a
 * modern runtime, and its GLSL 1.20 shaders are not ES-compatible. The
 * scene is rendered straight into the runtime's own swapchain images.
 *
 * The frame is spread across the five entry points share/state.c and
 * share/video.c already call, in this order:
 *
 *     hmd_poll()        xrWaitFrame, xrBeginFrame, xrLocateViews
 *     hmd_prep_left()   acquire the left image, bind its framebuffer
 *     hmd_persp()       load that eye's projection and view
 *     hmd_prep_right()  release the left image, acquire the right
 *     hmd_swap()        release the right image, xrEndFrame
 *
 * share/state.c:159-188 guarantees the strict left-right-swap ordering that
 * lets the release of one eye's image ride along with the acquisition of the
 * next, which is why no extra hook is needed in share/hmd.h.
 */

#include <SDL.h>
#include <SDL_system.h>

#include <EGL/egl.h>

#include <dlfcn.h>

#include <jni.h>

#include <math.h>
#include <stdlib.h>
#include <string.h>

#include "glext.h"
#include "hmd.h"
#include "hmd_math.h"
#include "log.h"
#include "video.h"

#define XR_USE_PLATFORM_ANDROID
#define XR_USE_GRAPHICS_API_OPENGL_ES
#include <openxr/openxr.h>
#include <openxr/openxr_platform.h>

/*---------------------------------------------------------------------------*/

#define EYE_COUNT 2

/* Fraction of the runtime's recommended per-eye resolution to render at. */

#define EYE_SCALE_NUM 7
#define EYE_SCALE_DEN 10

/* Report an OpenXR failure and bail out of the calling function. */

#define XR_TRY(expr)                                                    \
    do {                                                                \
        XrResult res_ = (expr);                                         \
        if (XR_FAILED(res_))                                            \
        {                                                               \
            log_printf("HMD: %s failed (%d) at %s:%d\n", #expr,         \
                       (int) res_, __FILE__, __LINE__);                 \
            return 0;                                                   \
        }                                                               \
    } while (0)

/*
 * The swapchain images belong to the runtime, not to gl4es, and that
 * distinction matters more than it looks.
 *
 * gl4es virtualizes texture names: gl4es_getTexture() looks a name up in its
 * own table and, for one it did not create, quietly generates a fresh real
 * texture and remaps to it. Handing it a swapchain image therefore produces
 * a framebuffer that is complete, that clears and draws without error, and
 * that the compositor never sees, because the colour attachment is a texture
 * gl4es invented. The result is a black headset.
 *
 * Framebuffer names are not virtualized, so the way out is narrow: build the
 * eye framebuffers with the driver's own entry points, and let gl4es do
 * nothing but bind them by name and draw.
 */

static void (*gles_FramebufferTexture2D)(GLenum, GLenum, GLenum, GLuint, GLint);
static void (*gles_FramebufferRenderbuffer)(GLenum, GLenum, GLenum, GLuint);
static void (*gles_GenRenderbuffers)(GLsizei, GLuint *);
static void (*gles_BindRenderbuffer)(GLenum, GLuint);
static void (*gles_RenderbufferStorage)(GLenum, GLenum, GLsizei, GLsizei);
static void (*gles_DeleteRenderbuffers)(GLsizei, const GLuint *);
static GLenum (*gles_CheckFramebufferStatus)(GLenum);

static int load_gles(void)
{
    static const char *names[] = { "libGLESv3.so", "libGLESv2.so", NULL };

    void *lib = NULL;
    int i;

    if (gles_FramebufferTexture2D)
        return 1;

    for (i = 0; names[i] && !lib; i++)
        lib = dlopen(names[i], RTLD_LAZY | RTLD_LOCAL);

    if (!lib)
    {
        log_printf("HMD: cannot open the GLES driver (%s)\n", dlerror());
        return 0;
    }

    *(void **) &gles_FramebufferTexture2D =
        dlsym(lib, "glFramebufferTexture2D");
    *(void **) &gles_FramebufferRenderbuffer =
        dlsym(lib, "glFramebufferRenderbuffer");
    *(void **) &gles_GenRenderbuffers    = dlsym(lib, "glGenRenderbuffers");
    *(void **) &gles_BindRenderbuffer    = dlsym(lib, "glBindRenderbuffer");
    *(void **) &gles_RenderbufferStorage = dlsym(lib, "glRenderbufferStorage");
    *(void **) &gles_DeleteRenderbuffers = dlsym(lib, "glDeleteRenderbuffers");
    *(void **) &gles_CheckFramebufferStatus =
        dlsym(lib, "glCheckFramebufferStatus");

    if (!gles_FramebufferTexture2D    || !gles_FramebufferRenderbuffer ||
        !gles_GenRenderbuffers        || !gles_BindRenderbuffer        ||
        !gles_RenderbufferStorage     || !gles_DeleteRenderbuffers     ||
        !gles_CheckFramebufferStatus)
    {
        log_printf("HMD: the GLES driver is missing framebuffer entry "
                   "points\n");

        gles_FramebufferTexture2D = NULL;
        return 0;
    }

    return 1;
}

struct eye_swapchain
{
    XrSwapchain                  handle;
    uint32_t                     image_count;
    XrSwapchainImageOpenGLESKHR *images;
    GLuint                      *fbos;
    GLuint                       depth;
    int32_t                      w, h;
};

static XrInstance     xr_instance = XR_NULL_HANDLE;
static XrSystemId     xr_system   = XR_NULL_SYSTEM_ID;
static XrSession      xr_session  = XR_NULL_HANDLE;
static XrSpace        xr_space    = XR_NULL_HANDLE;
static XrSessionState xr_state    = XR_SESSION_STATE_UNKNOWN;

static int xr_local_floor;
static int xr_running;

static struct eye_swapchain  xr_eye[EYE_COUNT];
static XrView                xr_views[EYE_COUNT];
static XrCompositionLayerProjectionView xr_layer_views[EYE_COUNT];

static XrTime xr_display_time;

/* Frame state, all reset by hmd_poll(). */

static int frame_begun;
static int should_render;
static int views_valid;

/* Which eye is being painted, and which of its images is bound. */

static int      cur_eye = 0;
static int      acquired_eye = -1;
static uint32_t acquired_index = 0;

/*---------------------------------------------------------------------------*/
/* Initialization                                                            */

static int xr_init_loader(void)
{
    PFN_xrInitializeLoaderKHR pfn = NULL;

    JNIEnv *env = SDL_AndroidGetJNIEnv();
    JavaVM *vm  = NULL;

    XrLoaderInitInfoAndroidKHR info;

    if (!env)
    {
        log_printf("HMD: SDL_AndroidGetJNIEnv returned NULL\n");
        return 0;
    }

    (*env)->GetJavaVM(env, &vm);

    XR_TRY(xrGetInstanceProcAddr(XR_NULL_HANDLE, "xrInitializeLoaderKHR",
                                 (PFN_xrVoidFunction *) &pfn));

    memset(&info, 0, sizeof (info));
    info.type               = XR_TYPE_LOADER_INIT_INFO_ANDROID_KHR;
    info.applicationVM      = vm;
    info.applicationContext = (jobject) SDL_AndroidGetActivity();

    XR_TRY(pfn((const XrLoaderInitInfoBaseHeaderKHR *) &info));

    return 1;
}

static int xr_has_extension(const XrExtensionProperties *p, uint32_t n,
                            const char *name)
{
    uint32_t i;

    for (i = 0; i < n; i++)
        if (strcmp(p[i].extensionName, name) == 0)
            return 1;

    return 0;
}

static int xr_init_instance(void)
{
    XrExtensionProperties *props = NULL;
    uint32_t count = 0, i;

    const char *enabled[4];
    uint32_t    enabled_count = 0;

    XrInstanceCreateInfo           create;
    XrInstanceCreateInfoAndroidKHR android;
    XrSystemGetInfo                sys;

    JNIEnv *env = SDL_AndroidGetJNIEnv();
    JavaVM *vm  = NULL;

    (*env)->GetJavaVM(env, &vm);

    XR_TRY(xrEnumerateInstanceExtensionProperties(NULL, 0, &count, NULL));

    if (!(props = calloc(count, sizeof (*props))))
        return 0;

    for (i = 0; i < count; i++)
        props[i].type = XR_TYPE_EXTENSION_PROPERTIES;

    if (XR_FAILED(xrEnumerateInstanceExtensionProperties(NULL, count, &count,
                                                         props)))
    {
        free(props);
        return 0;
    }

    if (!xr_has_extension(props, count, XR_KHR_OPENGL_ES_ENABLE_EXTENSION_NAME))
    {
        log_printf("HMD: runtime lacks %s\n",
                   XR_KHR_OPENGL_ES_ENABLE_EXTENSION_NAME);
        free(props);
        return 0;
    }

    enabled[enabled_count++] = XR_KHR_OPENGL_ES_ENABLE_EXTENSION_NAME;
    enabled[enabled_count++] = XR_KHR_ANDROID_CREATE_INSTANCE_EXTENSION_NAME;

    if (xr_has_extension(props, count, XR_EXT_LOCAL_FLOOR_EXTENSION_NAME))
    {
        enabled[enabled_count++] = XR_EXT_LOCAL_FLOOR_EXTENSION_NAME;
        xr_local_floor = 1;
    }

    free(props);

    memset(&android, 0, sizeof (android));
    android.type                = XR_TYPE_INSTANCE_CREATE_INFO_ANDROID_KHR;
    android.applicationVM       = vm;
    android.applicationActivity = (jobject) SDL_AndroidGetActivity();

    memset(&create, 0, sizeof (create));
    create.type = XR_TYPE_INSTANCE_CREATE_INFO;
    create.next = &android;
    create.enabledExtensionCount = enabled_count;
    create.enabledExtensionNames = enabled;
    strcpy(create.applicationInfo.applicationName, "Neverball");
    strcpy(create.applicationInfo.engineName,      "Neverball");
    create.applicationInfo.applicationVersion = 1;
    create.applicationInfo.engineVersion      = 1;
    create.applicationInfo.apiVersion         = XR_CURRENT_API_VERSION;

    XR_TRY(xrCreateInstance(&create, &xr_instance));

    memset(&sys, 0, sizeof (sys));
    sys.type       = XR_TYPE_SYSTEM_GET_INFO;
    sys.formFactor = XR_FORM_FACTOR_HEAD_MOUNTED_DISPLAY;

    XR_TRY(xrGetSystem(xr_instance, &sys, &xr_system));

    {
        XrInstanceProperties ip;

        memset(&ip, 0, sizeof (ip));
        ip.type = XR_TYPE_INSTANCE_PROPERTIES;

        if (XR_SUCCEEDED(xrGetInstanceProperties(xr_instance, &ip)))
            log_printf("HMD: OpenXR runtime \"%s\"\n", ip.runtimeName);
    }

    return 1;
}

static int xr_init_session(void)
{
    PFN_xrGetOpenGLESGraphicsRequirementsKHR pfn = NULL;
    XrGraphicsRequirementsOpenGLESKHR req;

    XrGraphicsBindingOpenGLESAndroidKHR bind;
    XrSessionCreateInfo                 create;
    XrReferenceSpaceCreateInfo          space;

    XrReferenceSpaceType *types = NULL;
    uint32_t              type_count = 0, i;
    XrReferenceSpaceType  chosen = XR_REFERENCE_SPACE_TYPE_LOCAL;

    /*
     * Take the EGL triple from the context SDL already created rather than
     * making one of our own. This keeps the SDL_GL_GetProcAddress ordering
     * that gl4es was initialized with in share/video.c intact.
     */

    EGLDisplay dpy = eglGetCurrentDisplay();
    EGLContext ctx = eglGetCurrentContext();
    EGLConfig  cfg = NULL;
    EGLint     cfg_id = 0, n = 0;

    if (dpy == EGL_NO_DISPLAY || ctx == EGL_NO_CONTEXT)
    {
        log_printf("HMD: no current EGL context to bind\n");
        return 0;
    }

    if (!eglQueryContext(dpy, ctx, EGL_CONFIG_ID, &cfg_id))
    {
        log_printf("HMD: eglQueryContext(EGL_CONFIG_ID) failed\n");
        return 0;
    }

    {
        const EGLint attrs[] = { EGL_CONFIG_ID, cfg_id, EGL_NONE };

        if (!eglChooseConfig(dpy, attrs, &cfg, 1, &n) || n != 1)
        {
            log_printf("HMD: could not recover EGLConfig %d\n", (int) cfg_id);
            return 0;
        }
    }

    /* The runtime requires this query before session creation. */

    XR_TRY(xrGetInstanceProcAddr(xr_instance,
                                 "xrGetOpenGLESGraphicsRequirementsKHR",
                                 (PFN_xrVoidFunction *) &pfn));

    memset(&req, 0, sizeof (req));
    req.type = XR_TYPE_GRAPHICS_REQUIREMENTS_OPENGL_ES_KHR;

    XR_TRY(pfn(xr_instance, xr_system, &req));

    memset(&bind, 0, sizeof (bind));
    bind.type    = XR_TYPE_GRAPHICS_BINDING_OPENGL_ES_ANDROID_KHR;
    bind.display = dpy;
    bind.config  = cfg;
    bind.context = ctx;

    memset(&create, 0, sizeof (create));
    create.type     = XR_TYPE_SESSION_CREATE_INFO;
    create.next     = &bind;
    create.systemId = xr_system;

    XR_TRY(xrCreateSession(xr_instance, &create, &xr_session));

    /* Prefer a floor-relative origin, so the chase camera sits at a sane
     * height without having to guess the player's stature. */

    XR_TRY(xrEnumerateReferenceSpaces(xr_session, 0, &type_count, NULL));

    if (!(types = calloc(type_count, sizeof (*types))))
        return 0;

    if (XR_FAILED(xrEnumerateReferenceSpaces(xr_session, type_count,
                                             &type_count, types)))
    {
        free(types);
        return 0;
    }

    for (i = 0; i < type_count; i++)
    {
        if (xr_local_floor &&
            types[i] == XR_REFERENCE_SPACE_TYPE_LOCAL_FLOOR_EXT)
        {
            chosen = types[i];
            break;
        }

        if (types[i] == XR_REFERENCE_SPACE_TYPE_STAGE &&
            chosen != XR_REFERENCE_SPACE_TYPE_LOCAL_FLOOR_EXT)
            chosen = types[i];
    }

    free(types);

    memset(&space, 0, sizeof (space));
    space.type               = XR_TYPE_REFERENCE_SPACE_CREATE_INFO;
    space.referenceSpaceType = chosen;
    space.poseInReferenceSpace.orientation.w = 1.0f;

    XR_TRY(xrCreateReferenceSpace(xr_session, &space, &xr_space));

    return 1;
}

static int xr_init_swapchains(void)
{
    XrViewConfigurationView config_views[EYE_COUNT];

    uint32_t count = 0, i, j;
    int64_t *formats = NULL;
    int64_t  chosen  = 0;

    XR_TRY(xrEnumerateViewConfigurationViews(
               xr_instance, xr_system,
               XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO,
               0, &count, NULL));

    if (count != EYE_COUNT)
    {
        log_printf("HMD: expected %d views, runtime reports %u\n",
                   EYE_COUNT, count);
        return 0;
    }

    for (i = 0; i < EYE_COUNT; i++)
    {
        memset(&config_views[i], 0, sizeof (config_views[i]));
        config_views[i].type = XR_TYPE_VIEW_CONFIGURATION_VIEW;
    }

    XR_TRY(xrEnumerateViewConfigurationViews(
               xr_instance, xr_system,
               XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO,
               count, &count, config_views));

    XR_TRY(xrEnumerateSwapchainFormats(xr_session, 0, &count, NULL));

    if (!(formats = calloc(count, sizeof (*formats))))
        return 0;

    if (XR_FAILED(xrEnumerateSwapchainFormats(xr_session, count, &count,
                                              formats)))
    {
        free(formats);
        return 0;
    }

    for (i = 0; i < count; i++)
    {
        if (formats[i] == GL_SRGB8_ALPHA8)
        {
            chosen = formats[i];
            break;
        }

        if (formats[i] == GL_RGBA8 && !chosen)
            chosen = formats[i];
    }

    free(formats);

    if (!chosen)
    {
        log_printf("HMD: no usable swapchain format\n");
        return 0;
    }

    log_printf("HMD: swapchain format 0x%x\n", (unsigned) chosen);

    for (i = 0; i < EYE_COUNT; i++)
    {
        struct eye_swapchain *e = &xr_eye[i];
        XrSwapchainCreateInfo info;

        e->w = (int32_t) (config_views[i].recommendedImageRectWidth *
                          EYE_SCALE_NUM / EYE_SCALE_DEN);
        e->h = (int32_t) (config_views[i].recommendedImageRectHeight *
                          EYE_SCALE_NUM / EYE_SCALE_DEN);

        memset(&info, 0, sizeof (info));
        info.type        = XR_TYPE_SWAPCHAIN_CREATE_INFO;
        info.usageFlags  = XR_SWAPCHAIN_USAGE_COLOR_ATTACHMENT_BIT |
                           XR_SWAPCHAIN_USAGE_SAMPLED_BIT;
        info.format      = chosen;
        info.sampleCount = 1;
        info.width       = (uint32_t) e->w;
        info.height      = (uint32_t) e->h;
        info.faceCount   = 1;
        info.arraySize   = 1;
        info.mipCount    = 1;

        XR_TRY(xrCreateSwapchain(xr_session, &info, &e->handle));

        XR_TRY(xrEnumerateSwapchainImages(e->handle, 0, &e->image_count, NULL));

        e->images = calloc(e->image_count, sizeof (*e->images));
        e->fbos   = calloc(e->image_count, sizeof (*e->fbos));

        if (!e->images || !e->fbos)
            return 0;

        for (j = 0; j < e->image_count; j++)
            e->images[j].type = XR_TYPE_SWAPCHAIN_IMAGE_OPENGL_ES_KHR;

        XR_TRY(xrEnumerateSwapchainImages(
                   e->handle, e->image_count, &e->image_count,
                   (XrSwapchainImageBaseHeader *) e->images));

        /*
         * One depth-plus-stencil buffer per eye, shared by all of that eye's
         * images, since they are rendered strictly in sequence. The stencil
         * is not optional: ball/game_draw.c:520-556 masks reflections with
         * it whenever CONFIG_REFLECTION is on.
         */

        gles_GenRenderbuffers(1, &e->depth);
        gles_BindRenderbuffer(GL_RENDERBUFFER, e->depth);
        gles_RenderbufferStorage(GL_RENDERBUFFER, GL_DEPTH24_STENCIL8,
                                 e->w, e->h);
        gles_BindRenderbuffer(GL_RENDERBUFFER, 0);

        /* The framebuffer names themselves come from gl4es, which passes
         * them straight through, so that binding one by name later leaves
         * its state tracking telling the truth. */

        glGenFramebuffers(e->image_count, e->fbos);

        for (j = 0; j < e->image_count; j++)
        {
            GLenum status;

            glBindFramebuffer(GL_FRAMEBUFFER, e->fbos[j]);

            gles_FramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0,
                                      GL_TEXTURE_2D, e->images[j].image, 0);
            gles_FramebufferRenderbuffer(GL_FRAMEBUFFER, GL_DEPTH_ATTACHMENT,
                                         GL_RENDERBUFFER, e->depth);
            gles_FramebufferRenderbuffer(GL_FRAMEBUFFER, GL_STENCIL_ATTACHMENT,
                                         GL_RENDERBUFFER, e->depth);

            status = gles_CheckFramebufferStatus(GL_FRAMEBUFFER);

            if (status != GL_FRAMEBUFFER_COMPLETE)
            {
                log_printf("HMD: eye %u image %u framebuffer incomplete "
                           "(0x%x)\n", i, j, (unsigned int) status);
                return 0;
            }
        }

        glBindFramebuffer(GL_FRAMEBUFFER, 0);

        log_printf("HMD: eye %u swapchain %dx%d of %ux%u recommended, "
                   "%u images\n", i, e->w, e->h,
                   config_views[i].recommendedImageRectWidth,
                   config_views[i].recommendedImageRectHeight,
                   e->image_count);
    }

    for (i = 0; i < EYE_COUNT; i++)
    {
        memset(&xr_views[i], 0, sizeof (xr_views[i]));
        xr_views[i].type = XR_TYPE_VIEW;
    }

    return 1;
}

/*---------------------------------------------------------------------------*/

int hmd_stat(void)
{
    return xr_session != XR_NULL_HANDLE;
}

void hmd_init(void)
{
    if (!load_gles())        { hmd_free(); return; }
    if (!xr_init_loader())   { hmd_free(); return; }
    if (!xr_init_instance()) { hmd_free(); return; }
    if (!xr_init_session())  { hmd_free(); return; }

    if (!xr_init_swapchains())
    {
        hmd_free();
        return;
    }

    /*
     * From here on the render target is a swapchain image, not the window,
     * so the rest of the engine has to size itself against that. This runs
     * after video_resize() in video_mode(), which set these from the window.
     */

    video.device_w     = xr_eye[0].w;
    video.device_h     = xr_eye[0].h;
    video.device_scale = 1.0f;
}

void hmd_free(void)
{
    int i;

    for (i = 0; i < EYE_COUNT; i++)
    {
        struct eye_swapchain *e = &xr_eye[i];

        if (e->fbos)
        {
            glDeleteFramebuffers(e->image_count, e->fbos);
            free(e->fbos);
        }

        if (e->depth)
            gles_DeleteRenderbuffers(1, &e->depth);

        if (e->handle != XR_NULL_HANDLE)
            xrDestroySwapchain(e->handle);

        free(e->images);

        memset(e, 0, sizeof (*e));
    }

    if (xr_space   != XR_NULL_HANDLE) xrDestroySpace(xr_space);
    if (xr_session != XR_NULL_HANDLE) xrDestroySession(xr_session);
    if (xr_instance != XR_NULL_HANDLE) xrDestroyInstance(xr_instance);

    xr_space    = XR_NULL_HANDLE;
    xr_session  = XR_NULL_HANDLE;
    xr_instance = XR_NULL_HANDLE;
    xr_system   = XR_NULL_SYSTEM_ID;
    xr_state    = XR_SESSION_STATE_UNKNOWN;

    xr_running    = 0;
    frame_begun   = 0;
    should_render = 0;
    views_valid   = 0;
    acquired_eye  = -1;
}

/*---------------------------------------------------------------------------*/
/* Per-frame                                                                 */

static void end_frame(int layer_count)
{
    XrFrameEndInfo end;
    const XrCompositionLayerBaseHeader *layers[1];
    XrCompositionLayerProjection layer;

    if (!frame_begun)
        return;

    memset(&end, 0, sizeof (end));
    end.type                 = XR_TYPE_FRAME_END_INFO;
    end.displayTime          = xr_display_time;
    end.environmentBlendMode = XR_ENVIRONMENT_BLEND_MODE_OPAQUE;

    if (layer_count)
    {
        memset(&layer, 0, sizeof (layer));
        layer.type      = XR_TYPE_COMPOSITION_LAYER_PROJECTION;
        layer.space     = xr_space;
        layer.viewCount = EYE_COUNT;
        layer.views     = xr_layer_views;

        layers[0] = (const XrCompositionLayerBaseHeader *) &layer;

        end.layerCount = 1;
        end.layers     = layers;
    }

    xrEndFrame(xr_session, &end);

    frame_begun = 0;
}

static void poll_events(void)
{
    XrEventDataBuffer ev;

    for (;;)
    {
        memset(&ev, 0, sizeof (ev));
        ev.type = XR_TYPE_EVENT_DATA_BUFFER;

        if (xrPollEvent(xr_instance, &ev) != XR_SUCCESS)
            break;

        switch (ev.type)
        {
        case XR_TYPE_EVENT_DATA_SESSION_STATE_CHANGED:
        {
            const XrEventDataSessionStateChanged *e =
                (const XrEventDataSessionStateChanged *) &ev;

            xr_state = e->state;

            log_printf("HMD: session state %d\n", (int) xr_state);

            if (xr_state == XR_SESSION_STATE_READY)
            {
                XrSessionBeginInfo begin;

                memset(&begin, 0, sizeof (begin));
                begin.type = XR_TYPE_SESSION_BEGIN_INFO;
                begin.primaryViewConfigurationType =
                    XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO;

                if (XR_SUCCEEDED(xrBeginSession(xr_session, &begin)))
                    xr_running = 1;
            }
            else if (xr_state == XR_SESSION_STATE_STOPPING)
            {
                xr_running = 0;
                xrEndSession(xr_session);
            }
            else if (xr_state == XR_SESSION_STATE_EXITING ||
                     xr_state == XR_SESSION_STATE_LOSS_PENDING)
            {
                SDL_Event quit;

                xr_running = 0;

                memset(&quit, 0, sizeof (quit));
                quit.type = SDL_QUIT;
                SDL_PushEvent(&quit);
            }

            break;
        }

        case XR_TYPE_EVENT_DATA_INSTANCE_LOSS_PENDING:
        {
            SDL_Event quit;

            memset(&quit, 0, sizeof (quit));
            quit.type = SDL_QUIT;
            SDL_PushEvent(&quit);

            break;
        }

        default:
            break;
        }
    }
}

void hmd_poll(void)
{
    XrFrameWaitInfo  wait;
    XrFrameState     state;
    XrFrameBeginInfo begin;

    XrViewLocateInfo locate;
    XrViewState      view_state;
    uint32_t         view_count = EYE_COUNT;

    if (!hmd_stat())
        return;

    /*
     * A frame still open here means the caller skipped its paint after we
     * began one. Close it empty rather than leaving xrBeginFrame unbalanced.
     */

    if (frame_begun)
    {
        acquired_eye = -1;
        end_frame(0);
    }

    should_render = 0;
    views_valid   = 0;

    poll_events();

    if (!xr_running)
    {
        /* No session to pace us, so do not spin. */

        SDL_Delay(10);
        return;
    }

    memset(&wait, 0, sizeof (wait));
    wait.type = XR_TYPE_FRAME_WAIT_INFO;

    memset(&state, 0, sizeof (state));
    state.type = XR_TYPE_FRAME_STATE;

    if (XR_FAILED(xrWaitFrame(xr_session, &wait, &state)))
        return;

    xr_display_time = state.predictedDisplayTime;

    memset(&begin, 0, sizeof (begin));
    begin.type = XR_TYPE_FRAME_BEGIN_INFO;

    if (XR_FAILED(xrBeginFrame(xr_session, &begin)))
        return;

    frame_begun = 1;

    memset(&view_state, 0, sizeof (view_state));
    view_state.type = XR_TYPE_VIEW_STATE;

    memset(&locate, 0, sizeof (locate));
    locate.type                  = XR_TYPE_VIEW_LOCATE_INFO;
    locate.viewConfigurationType = XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO;
    locate.displayTime           = xr_display_time;
    locate.space                 = xr_space;

    if (XR_SUCCEEDED(xrLocateViews(xr_session, &locate, &view_state,
                                   EYE_COUNT, &view_count, xr_views)))
        views_valid =
            (view_state.viewStateFlags & XR_VIEW_STATE_POSITION_VALID_BIT) &&
            (view_state.viewStateFlags & XR_VIEW_STATE_ORIENTATION_VALID_BIT);

    if (state.shouldRender && views_valid)
        should_render = 1;
    else
        end_frame(0);
}

int hmd_should_render(void)
{
    return !hmd_stat() || should_render;
}

void hmd_step(void)
{
}

/*---------------------------------------------------------------------------*/

static void release_eye(void)
{
    if (acquired_eye >= 0)
    {
        XrSwapchainImageReleaseInfo rel;

        memset(&rel, 0, sizeof (rel));
        rel.type = XR_TYPE_SWAPCHAIN_IMAGE_RELEASE_INFO;

        xrReleaseSwapchainImage(xr_eye[acquired_eye].handle, &rel);

        acquired_eye = -1;
    }
}

static void prep_eye(int eye)
{
    struct eye_swapchain *e = &xr_eye[eye];

    XrSwapchainImageAcquireInfo acq;
    XrSwapchainImageWaitInfo    wait;

    cur_eye = eye;

    if (!should_render)
        return;

    release_eye();

    memset(&acq, 0, sizeof (acq));
    acq.type = XR_TYPE_SWAPCHAIN_IMAGE_ACQUIRE_INFO;

    if (XR_FAILED(xrAcquireSwapchainImage(e->handle, &acq, &acquired_index)))
        return;

    memset(&wait, 0, sizeof (wait));
    wait.type    = XR_TYPE_SWAPCHAIN_IMAGE_WAIT_INFO;
    wait.timeout = XR_INFINITE_DURATION;

    if (XR_FAILED(xrWaitSwapchainImage(e->handle, &wait)))
        return;

    acquired_eye = eye;

    glBindFramebuffer(GL_FRAMEBUFFER, e->fbos[acquired_index]);
    glViewport(0, 0, e->w, e->h);
    glScissor (0, 0, e->w, e->h);

    /* Describe what is about to be painted, for the layer at end of frame. */

    memset(&xr_layer_views[eye], 0, sizeof (xr_layer_views[eye]));
    xr_layer_views[eye].type = XR_TYPE_COMPOSITION_LAYER_PROJECTION_VIEW;
    xr_layer_views[eye].pose = xr_views[eye].pose;
    xr_layer_views[eye].fov  = xr_views[eye].fov;
    xr_layer_views[eye].subImage.swapchain               = e->handle;
    xr_layer_views[eye].subImage.imageRect.offset.x      = 0;
    xr_layer_views[eye].subImage.imageRect.offset.y      = 0;
    xr_layer_views[eye].subImage.imageRect.extent.width  = e->w;
    xr_layer_views[eye].subImage.imageRect.extent.height = e->h;
    xr_layer_views[eye].subImage.imageArrayIndex         = 0;
}

void hmd_prep_left(void)
{
    prep_eye(0);
}

void hmd_prep_right(void)
{
    prep_eye(1);
}

void hmd_swap(void)
{
    release_eye();

    glBindFramebuffer(GL_FRAMEBUFFER, 0);

    end_frame(should_render ? 1 : 0);
}

/*---------------------------------------------------------------------------*/

void hmd_persp(float n, float f)
{
    const XrFovf  *fov  = &xr_views[cur_eye].fov;
    const XrPosef *pose = &xr_views[cur_eye].pose;

    float t[4];
    float q[4];
    float p[3];

    float P[16];
    float V[16];

    t[0] = tanf(fov->angleLeft);
    t[1] = tanf(fov->angleRight);
    t[2] = tanf(fov->angleDown);
    t[3] = tanf(fov->angleUp);

    q[0] = pose->orientation.x;
    q[1] = pose->orientation.y;
    q[2] = pose->orientation.z;
    q[3] = pose->orientation.w;

    p[0] = pose->position.x;
    p[1] = pose->position.y;
    p[2] = pose->position.z;

    hmd_frustum(P, t, n, f);
    hmd_view   (V, q, p);

    glMatrixMode(GL_PROJECTION);
    glLoadMatrixf(P);

    glMatrixMode(GL_MODELVIEW);
    glLoadMatrixf(V);
}

/*
 * Place the pixel-space GUI on a world-locked quad in front of the reference
 * space origin. Head-locked panels are far less comfortable to read, and a
 * world-locked one can be looked away from.
 */

void hmd_ortho(void)
{
    const float dist   = 2.00f;   /* metres in front of the origin */
    const float height = 1.50f;   /* metres above the floor        */
    const float span   = 1.60f;   /* metres the GUI height spans   */

    const float s = span / (float) video.device_h;

    hmd_persp(0.1f, 100.0f);

    glTranslatef(0.0f, height, -dist);
    glScalef(s, s, s);
    glTranslatef(-0.5f * (float) video.device_w,
                 -0.5f * (float) video.device_h, 0.0f);
}

/*---------------------------------------------------------------------------*/
