/* Generated by Claude Code 2.1.263 (claude-opus-5[1m]) */

#ifndef HMD_OPENXR_H
#define HMD_OPENXR_H

/*---------------------------------------------------------------------------*/

/*
 * The parts of the OpenXR session that the input backend needs to share with
 * the display backend. Actions belong to the same session and are located in
 * the same space at the same predicted display time, so there is no sensible
 * way to keep the two entirely apart -- but this is the whole of the seam.
 */

#define XR_USE_PLATFORM_ANDROID
#define XR_USE_GRAPHICS_API_OPENGL_ES
#include <openxr/openxr.h>

XrInstance hmd_xr_instance(void);
XrSession  hmd_xr_session(void);
XrSpace    hmd_xr_space(void);

/* The predicted display time of the frame being built, or 0 before one is. */

XrTime     hmd_xr_time(void);

/*---------------------------------------------------------------------------*/

#endif
