/* Generated by Claude Code 2.1.263 (claude-opus-5[1m]) */

#ifndef HMD_MATH_H
#define HMD_MATH_H

/*---------------------------------------------------------------------------*/

/*
 * Matrix helpers for the HMD backends. They are kept free of any XR runtime's
 * types so that the awkward parts -- an off-centre frustum and the inverse of
 * a quaternion pose -- can be exercised on the host, where the headset that
 * would otherwise be the only way to notice a mirrored axis is not needed.
 *
 * All matrices are 16 floats in column-major order, as glLoadMatrixf wants.
 */

/*
 * An asymmetric perspective projection. The four tangents are of the signed
 * half-angles to the left, right, bottom and top frustum planes, in that
 * order, measured at unit distance. The symmetric case is t[1] == -t[0] and
 * t[3] == -t[2].
 */

void hmd_frustum(float *M, const float t[4], float n, float f);

/*
 * The view matrix of a rigid pose: the inverse of the transform that places
 * an object at position p with orientation q. The quaternion is stored
 * x, y, z, w and is assumed to be unit length.
 */

void hmd_view(float *M, const float q[4], const float p[3]);

/*---------------------------------------------------------------------------*/

#endif
