/* Generated by Claude Code 2.1.263 (claude-opus-5[1m]) */

#include <math.h>

#include "vr.h"

/*---------------------------------------------------------------------------*/

/* Camera speed, in metres per second, at which the vignette is fully in. */

#define SPEED_FULL 10.0f

/* Camera yaw rate, in degrees per second, at which the same is true. */

#define YAW_FULL 120.0f

/*
 * Time constants for the response, in seconds. Closing has to be quicker
 * than opening: arriving late is the one failure that matters, and a
 * vignette that opens as eagerly as it closes flickers on every small
 * correction, which is its own kind of unpleasant.
 */

#define CLOSE_TIME 0.10f
#define OPEN_TIME  0.60f

/* Ignore camera motion below these, so a resting camera reads as still. */

#define SPEED_DEAD 0.60f
#define YAW_DEAD   8.00f

static float vignette;

static float last_p[3];
static float last_a;
static int   have_last;

/*---------------------------------------------------------------------------*/

void vr_comfort_reset(void)
{
    vignette  = 0.0f;
    have_last = 0;
}

/* The shorter way round between two angles in degrees. */

static float angle_delta(float a, float b)
{
    float d = fmodf(a - b, 360.0f);

    if (d >  180.0f) d -= 360.0f;
    if (d < -180.0f) d += 360.0f;

    return d;
}

static float unit(float v, float dead, float full)
{
    if (v <= dead)
        return 0.0f;

    v = (v - dead) / (full - dead);

    return v > 1.0f ? 1.0f : v;
}

void vr_comfort_step(float dt, const float p[3], float a)
{
    float d[3];
    float speed, yaw, target, rate;

    if (!(dt > 0.0f))
        return;

    if (!have_last)
    {
        last_p[0] = p[0];
        last_p[1] = p[1];
        last_p[2] = p[2];
        last_a    = a;
        have_last = 1;

        return;
    }

    d[0] = p[0] - last_p[0];
    d[1] = p[1] - last_p[1];
    d[2] = p[2] - last_p[2];

    speed = sqrtf(d[0] * d[0] + d[1] * d[1] + d[2] * d[2]) / dt;
    yaw   = fabsf(angle_delta(a, last_a)) / dt;

    last_p[0] = p[0];
    last_p[1] = p[1];
    last_p[2] = p[2];
    last_a    = a;

    /* Whichever of the two is worse decides. */

    target = unit(speed, SPEED_DEAD, SPEED_FULL);

    {
        float y = unit(yaw, YAW_DEAD, YAW_FULL);

        if (y > target)
            target = y;
    }

    rate = dt / (target > vignette ? CLOSE_TIME : OPEN_TIME);

    if (rate > 1.0f)
        rate = 1.0f;

    vignette += (target - vignette) * rate;
}

float vr_comfort_vignette(void)
{
    return vignette;
}

/*---------------------------------------------------------------------------*/

int vr_panel_hit(const float o[3], const float d[3], int w, int h,
                 int *x, int *y)
{
    /* The panel lies in the plane z = -VR_PANEL_DIST, facing +Z. */

    const float s = VR_PANEL_SPAN / (float) h;

    float t, hx, hy;

    if (!(d[2] < 0.0f))
        return 0;

    t = (-VR_PANEL_DIST - o[2]) / d[2];

    if (!(t > 0.0f))
        return 0;

    hx = o[0] + d[0] * t;
    hy = o[1] + d[1] * t;

    /* Undo the placement hmd_ortho() applies to the pixel-space interface. */

    *x = (int) (hx / s + 0.5f * (float) w);
    *y = (int) ((hy - VR_PANEL_HEIGHT) / s + 0.5f * (float) h);

    return 1;
}

/*---------------------------------------------------------------------------*/
