/* Generated by Claude Code 2.1.263 (claude-opus-5[1m]) */

#ifndef VR_H
#define VR_H

/*---------------------------------------------------------------------------*/

/*
 * Comfort state for the head-tracked chase camera.
 *
 * Neverball's camera swings and dollies in ways that are unremarkable on a
 * monitor and unpleasant in a headset, because the inner ear is not moving
 * along with the picture. This tracks how hard the camera is currently
 * throwing the player around, which the vignette then follows.
 *
 * There is no GL and no configuration here on purpose: the awkward part is
 * the smoothing, and it is worth being able to check that on the host.
 */

void  vr_comfort_reset(void);

/*
 * Feed the camera's position in metres and its yaw in degrees, once per
 * frame. dt of zero or less is ignored, so it is safe to call this from a
 * paint path that runs more than once per frame.
 */

void  vr_comfort_step(float dt, const float p[3], float a);

/*
 * How far the vignette should be closed, from 0 (fully open, nothing drawn)
 * to 1 (as closed as it ever gets).
 */

float vr_comfort_vignette(void);

/*---------------------------------------------------------------------------*/

#endif
