/* Generated by Claude Code 2.1.263 (claude-opus-5[1m]) */

#ifndef VR_H
#define VR_H

/*---------------------------------------------------------------------------*/

/*
 * Comfort state for the head-tracked chase camera.
 *
 * Neverball's camera swings and dollies in ways that are unremarkable on a
 * monitor and unpleasant in a headset, because the inner ear is not moving
 * along with the picture. This tracks how hard the camera is currently
 * throwing the player around, which the vignette then follows.
 *
 * There is no GL and no configuration here on purpose: the awkward part is
 * the smoothing, and it is worth being able to check that on the host.
 */

void  vr_comfort_reset(void);

/*
 * Feed the camera's position in metres and its yaw in degrees, once per
 * frame. dt of zero or less is ignored, so it is safe to call this from a
 * paint path that runs more than once per frame.
 */

void  vr_comfort_step(float dt, const float p[3], float a);

/*
 * How far the vignette should be closed, from 0 (fully open, nothing drawn)
 * to 1 (as closed as it ever gets).
 */

float vr_comfort_vignette(void);

/*---------------------------------------------------------------------------*/

/*
 * Where the pixel-space interface hangs in the world, in metres: a panel
 * VR_PANEL_DIST in front of the reference space origin and VR_PANEL_HEIGHT
 * above the floor, VR_PANEL_SPAN tall, facing back down +Z.
 *
 * A world-locked panel is far more comfortable to read than a head-locked
 * one, and it can be looked away from.
 */

#define VR_PANEL_DIST   2.00f
#define VR_PANEL_HEIGHT 1.50f
#define VR_PANEL_SPAN   1.60f

/*
 * Intersect a pointer ray with that panel and return where it lands, in the
 * interface's own pixel coordinates for a w by h layout, with the origin at
 * the bottom left as the rest of the code expects.
 *
 * Returns zero when the ray misses the plane or crosses it behind the
 * pointer; a hit outside the panel's own rectangle still returns its
 * coordinates, since the caller may want to know which way the player is
 * pointing rather than only whether they are on target.
 */

int vr_panel_hit(const float o[3], const float d[3], int w, int h,
                 int *x, int *y);

/*---------------------------------------------------------------------------*/

#endif
