/* Generated by Claude Code 2.1.263 (claude-opus-5[1m]) */

#ifndef VR_INPUT_H
#define VR_INPUT_H

/*---------------------------------------------------------------------------*/

/*
 * Motion controller input, pushed straight into the st_* interface the rest
 * of the game already listens to. There is no new abstraction here on
 * purpose: a headset controller is a joystick with a pose attached, and
 * Neverball already knows what to do with a joystick.
 */

void vr_input_init(void);
void vr_input_free(void);

/* Read the controllers once, at the top of a frame. */

void vr_input_poll(void);

/*---------------------------------------------------------------------------*/

#endif
