/* Generated by Claude Code 2.1.263 (claude-opus-5[1m]) */

/*
 * OpenXR motion controller input.
 *
 * Everything here ends up in the st_* interface that share/state.c already
 * exposes to keyboards, mice and joysticks, using the button and axis
 * numbers the configuration already defines. That is the same trick
 * ball/main.c:607-627 plays to turn a tilt sensor into D-pad presses, and it
 * means none of the game's states need to know a headset is involved.
 *
 * The one thing without an existing equivalent is the pointer ray, which
 * lands on the world-locked interface panel and is delivered as mouse
 * motion and clicks. share/gui.c's hit testing is then reused untouched.
 */

#include <math.h>
#include <string.h>

#include <SDL.h>

#include "vec3.h"
#include "hmd.h"
#include "hmd_openxr.h"
#include "vr.h"
#include "vr_input.h"
#include "config.h"
#include "state.h"
#include "video.h"
#include "log.h"

/*---------------------------------------------------------------------------*/

#define HAND_L 0
#define HAND_R 1
#define HANDS  2

static XrActionSet act_set;

static XrAction act_tilt;               /* left thumbstick,  Vector2f */
static XrAction act_look;               /* right thumbstick, Vector2f */
static XrAction act_aim [HANDS];        /* pointing pose              */
static XrAction act_grip;               /* right grip pose, for tilt  */
static XrAction act_select;             /* trigger                    */
static XrAction act_back;               /* B                          */
static XrAction act_start;              /* X                          */
static XrAction act_option;             /* Y                          */
static XrAction act_cam [HANDS];        /* grip squeeze               */

static XrSpace  spc_aim [HANDS];
static XrSpace  spc_grip;

static int ready;                       /* actions built and attached */
static int failed;                      /* and if not, do not retry   */

/*---------------------------------------------------------------------------*/

#define XR_TRY(expr)                                                    \
    do {                                                                \
        XrResult res_ = (expr);                                         \
        if (XR_FAILED(res_))                                            \
        {                                                               \
            log_printf("VR input: %s failed (%d)\n", #expr, (int) res_); \
            return 0;                                                   \
        }                                                               \
    } while (0)

static XrPath path(const char *s)
{
    XrPath p = XR_NULL_PATH;

    xrStringToPath(hmd_xr_instance(), s, &p);

    return p;
}

static int make_action(XrAction *a, XrActionType type, const char *name,
                       const char *label)
{
    XrActionCreateInfo info;

    memset(&info, 0, sizeof (info));
    info.type       = XR_TYPE_ACTION_CREATE_INFO;
    info.actionType = type;

    strncpy(info.actionName,          name,  XR_MAX_ACTION_NAME_SIZE - 1);
    strncpy(info.localizedActionName, label, XR_MAX_LOCALIZED_ACTION_NAME_SIZE - 1);

    XR_TRY(xrCreateAction(act_set, &info, a));

    return 1;
}

static int make_pose_space(XrSpace *s, XrAction a)
{
    XrActionSpaceCreateInfo info;

    memset(&info, 0, sizeof (info));
    info.type   = XR_TYPE_ACTION_SPACE_CREATE_INFO;
    info.action = a;
    info.poseInActionSpace.orientation.w = 1.0f;

    XR_TRY(xrCreateActionSpace(hmd_xr_session(), &info, s));

    return 1;
}

/*
 * Suggest one interaction profile's worth of bindings. A runtime is free to
 * reject a profile it does not know, which is why the result is not fatal:
 * the Touch bindings are what a Quest will use, and the simple controller is
 * a fallback that costs nothing to offer.
 */

static void suggest(const char *profile,
                    const XrActionSuggestedBinding *b, int n)
{
    XrInteractionProfileSuggestedBinding s;

    memset(&s, 0, sizeof (s));
    s.type                   = XR_TYPE_INTERACTION_PROFILE_SUGGESTED_BINDING;
    s.interactionProfile     = path(profile);
    s.countSuggestedBindings = (uint32_t) n;
    s.suggestedBindings      = b;

    if (XR_FAILED(xrSuggestInteractionProfileBindings(hmd_xr_instance(), &s)))
        log_printf("VR input: runtime declined bindings for %s\n", profile);
}

static int init_actions(void)
{
    XrActionSetCreateInfo set_info;
    XrSessionActionSetsAttachInfo attach;

    memset(&set_info, 0, sizeof (set_info));
    set_info.type = XR_TYPE_ACTION_SET_CREATE_INFO;
    strcpy(set_info.actionSetName,          "gameplay");
    strcpy(set_info.localizedActionSetName, "Gameplay");
    set_info.priority = 0;

    XR_TRY(xrCreateActionSet(hmd_xr_instance(), &set_info, &act_set));

    if (!make_action(&act_tilt,   XR_ACTION_TYPE_VECTOR2F_INPUT, "tilt",   "Tilt the floor")   ||
        !make_action(&act_look,   XR_ACTION_TYPE_VECTOR2F_INPUT, "look",   "Turn the camera")  ||
        !make_action(&act_aim[HAND_L], XR_ACTION_TYPE_POSE_INPUT, "aim_left",  "Point (left)")  ||
        !make_action(&act_aim[HAND_R], XR_ACTION_TYPE_POSE_INPUT, "aim_right", "Point (right)") ||
        !make_action(&act_grip,   XR_ACTION_TYPE_POSE_INPUT,     "wrist",  "Tilt by wrist")    ||
        !make_action(&act_select, XR_ACTION_TYPE_BOOLEAN_INPUT,  "select", "Select")           ||
        !make_action(&act_back,   XR_ACTION_TYPE_BOOLEAN_INPUT,  "back",   "Back")             ||
        !make_action(&act_start,  XR_ACTION_TYPE_BOOLEAN_INPUT,  "start",  "Pause")            ||
        !make_action(&act_option, XR_ACTION_TYPE_BOOLEAN_INPUT,  "option", "Options")          ||
        !make_action(&act_cam[HAND_L], XR_ACTION_TYPE_BOOLEAN_INPUT, "camera_left",  "Camera left")  ||
        !make_action(&act_cam[HAND_R], XR_ACTION_TYPE_BOOLEAN_INPUT, "camera_right", "Camera right"))
        return 0;

    {
        const XrActionSuggestedBinding touch[] = {
            { act_tilt,   path("/user/hand/left/input/thumbstick")     },
            { act_look,   path("/user/hand/right/input/thumbstick")    },
            { act_aim[HAND_L], path("/user/hand/left/input/aim/pose")  },
            { act_aim[HAND_R], path("/user/hand/right/input/aim/pose") },
            { act_grip,   path("/user/hand/right/input/grip/pose")     },
            { act_select, path("/user/hand/right/input/trigger/value") },
            { act_select, path("/user/hand/left/input/trigger/value")  },
            { act_select, path("/user/hand/right/input/a/click")       },
            { act_back,   path("/user/hand/right/input/b/click")       },
            { act_start,  path("/user/hand/left/input/x/click")        },
            { act_option, path("/user/hand/left/input/y/click")        },
            { act_cam[HAND_L], path("/user/hand/left/input/squeeze/value")  },
            { act_cam[HAND_R], path("/user/hand/right/input/squeeze/value") },
        };

        const XrActionSuggestedBinding simple[] = {
            { act_aim[HAND_L], path("/user/hand/left/input/aim/pose")  },
            { act_aim[HAND_R], path("/user/hand/right/input/aim/pose") },
            { act_grip,   path("/user/hand/right/input/grip/pose")     },
            { act_select, path("/user/hand/right/input/select/click")  },
            { act_select, path("/user/hand/left/input/select/click")   },
            { act_back,   path("/user/hand/right/input/menu/click")    },
            { act_start,  path("/user/hand/left/input/menu/click")     },
        };

        suggest("/interaction_profiles/oculus/touch_controller",
                touch, (int) (sizeof (touch) / sizeof (touch[0])));
        suggest("/interaction_profiles/khr/simple_controller",
                simple, (int) (sizeof (simple) / sizeof (simple[0])));
    }

    if (!make_pose_space(&spc_aim[HAND_L], act_aim[HAND_L]) ||
        !make_pose_space(&spc_aim[HAND_R], act_aim[HAND_R]) ||
        !make_pose_space(&spc_grip,        act_grip))
        return 0;

    memset(&attach, 0, sizeof (attach));
    attach.type                = XR_TYPE_SESSION_ACTION_SETS_ATTACH_INFO;
    attach.countActionSets     = 1;
    attach.actionSets          = &act_set;

    XR_TRY(xrAttachSessionActionSets(hmd_xr_session(), &attach));

    log_printf("VR input: action set attached\n");

    return 1;
}

/*---------------------------------------------------------------------------*/

static int get_vec2(XrAction a, float *x, float *y)
{
    XrActionStateGetInfo get;
    XrActionStateVector2f st;

    memset(&get, 0, sizeof (get));
    get.type   = XR_TYPE_ACTION_STATE_GET_INFO;
    get.action = a;

    memset(&st, 0, sizeof (st));
    st.type = XR_TYPE_ACTION_STATE_VECTOR2F;

    if (XR_FAILED(xrGetActionStateVector2f(hmd_xr_session(), &get, &st)) ||
        !st.isActive)
        return 0;

    *x = st.currentState.x;
    *y = st.currentState.y;

    return 1;
}

/* Report a button only when it changes, which is what st_buttn() expects. */

static int get_edge(XrAction a, int *down)
{
    XrActionStateGetInfo get;
    XrActionStateBoolean st;

    memset(&get, 0, sizeof (get));
    get.type   = XR_TYPE_ACTION_STATE_GET_INFO;
    get.action = a;

    memset(&st, 0, sizeof (st));
    st.type = XR_TYPE_ACTION_STATE_BOOLEAN;

    if (XR_FAILED(xrGetActionStateBoolean(hmd_xr_session(), &get, &st)) ||
        !st.isActive || !st.changedSinceLastSync)
        return 0;

    *down = st.currentState ? 1 : 0;

    return 1;
}

static int get_pose(XrSpace space, XrPosef *pose)
{
    XrSpaceLocation loc;

    memset(&loc, 0, sizeof (loc));
    loc.type = XR_TYPE_SPACE_LOCATION;

    if (XR_FAILED(xrLocateSpace(space, hmd_xr_space(), hmd_xr_time(), &loc)))
        return 0;

    if (!(loc.locationFlags & XR_SPACE_LOCATION_POSITION_VALID_BIT) ||
        !(loc.locationFlags & XR_SPACE_LOCATION_ORIENTATION_VALID_BIT))
        return 0;

    *pose = loc.pose;

    return 1;
}

/* The three axes of a pose's orientation, as the renderer would see them. */

static void pose_basis(const XrPosef *p, float right[3], float fwd[3])
{
    const float x = p->orientation.x;
    const float y = p->orientation.y;
    const float z = p->orientation.z;
    const float w = p->orientation.w;

    if (right)
    {
        right[0] = 1.0f - 2.0f * (y * y + z * z);
        right[1] =        2.0f * (x * y + z * w);
        right[2] =        2.0f * (x * z - y * w);
    }

    /* Forward is -Z, as it is everywhere else in this codebase. */

    if (fwd)
    {
        fwd[0] = -(       2.0f * (x * z + y * w));
        fwd[1] = -(       2.0f * (y * z - x * w));
        fwd[2] = -(1.0f - 2.0f * (x * x + y * y));
    }
}

/* How far an axis of the controller has tipped off horizontal, in degrees. */

static float tip_deg(float y)
{
    if (y >  1.0f) y =  1.0f;
    if (y < -1.0f) y = -1.0f;

    return V_DEG(asinf(y));
}

/*---------------------------------------------------------------------------*/

/* Only report an axis when it actually moves, as a joystick would. */

static void push_stick(int axis, float v, float *last)
{
    if (fabsf(v - *last) > 0.01f)
    {
        *last = v;
        st_stick(axis, v);
    }
}

static void poll_sticks(void)
{
    static float last_x0 = 0.0f, last_y0 = 0.0f, last_x1 = 0.0f;
    static int   turning = 0;

    float x, y;

    /*
     * The left stick always reports, because it is also how menus are
     * navigated. In wrist mode poll_wrist() runs afterwards and overrides
     * it, which only affects the playing state -- nothing else listens for
     * an angle.
     */

    if (get_vec2(act_tilt, &x, &y))
    {
        /* A thumbstick reads y as up; a joystick axis reads it as down. */

        push_stick(config_get_d(CONFIG_JOYSTICK_AXIS_X0), x, &last_x0);
        push_stick(config_get_d(CONFIG_JOYSTICK_AXIS_Y0), -y, &last_y0);
    }

    /*
     * The right stick is a two-way switch rather than an axis: pushing it
     * left or right asks for one step of camera rotation, and there is
     * nothing up or down -- a vertical camera swing in a headset is both
     * unpleasant and, with the chase camera already level, pointless.
     *
     * The two thresholds are deliberately apart. A stick resting near one
     * of them would otherwise chatter out a step every few frames, which
     * with a stepped turn is a spinning room rather than a small wobble.
     */

    if (get_vec2(act_look, &x, &y))
    {
        if (turning == 0)
        {
            if (x > +0.6f) turning = +1;
            if (x < -0.6f) turning = -1;
        }
        else if (fabsf(x) < 0.4f)
            turning = 0;

        push_stick(config_get_d(CONFIG_JOYSTICK_AXIS_X1),
                   (float) turning, &last_x1);
    }
}

static void poll_buttons(void)
{
    static const struct
    {
        XrAction *action;
        const int *button;
    } map[] = {
        { &act_back,        &CONFIG_JOYSTICK_BUTTON_B      },
        { &act_start,       &CONFIG_JOYSTICK_BUTTON_START  },
        { &act_option,      &CONFIG_JOYSTICK_BUTTON_SELECT },
        { &act_cam[HAND_L], &CONFIG_JOYSTICK_BUTTON_L1     },
        { &act_cam[HAND_R], &CONFIG_JOYSTICK_BUTTON_R1     },
    };

    size_t i;
    int down;

    /*
     * The trigger is both a click on whatever the pointer is over and the
     * A button, which is what makes a menu usable either by pointing at it
     * or by moving a highlight with the stick.
     */

    if (get_edge(act_select, &down))
        st_click(SDL_BUTTON_LEFT, down);

    for (i = 0; i < sizeof (map) / sizeof (map[0]); i++)
        if (get_edge(*map[i].action, &down))
            st_buttn(config_get_d(*map[i].button), down);
}

static void poll_pointer(void)
{
    static int last_x, last_y, have_last;

    XrPosef pose;
    float fwd[3];
    float o[3];
    int x, y;

    /* Prefer the right hand, and fall back to the left when it is not
     * being tracked, which is what a left-handed player will see. */

    if (!get_pose(spc_aim[HAND_R], &pose) &&
        !get_pose(spc_aim[HAND_L], &pose))
        return;

    pose_basis(&pose, NULL, fwd);

    o[0] = pose.position.x;
    o[1] = pose.position.y;
    o[2] = pose.position.z;

    if (!vr_panel_hit(o, fwd, video.device_w, video.device_h, &x, &y))
        return;

    st_point(x, y, have_last ? x - last_x : 0, have_last ? y - last_y : 0);

    last_x    = x;
    last_y    = y;
    have_last = 1;
}

static void poll_wrist(void)
{
    XrPosef pose;
    float right[3], fwd[3];

    if (!config_get_d(CONFIG_VR_CONTROL))
        return;

    if (!get_pose(spc_grip, &pose))
        return;

    pose_basis(&pose, right, fwd);

    /*
     * game_set_ang() clamps to ANGLE_BOUND, so tipping the controller twenty
     * degrees is full deflection -- about what it takes to feel like tilting
     * a tray.
     */

    st_angle(tip_deg(fwd[1]), tip_deg(-right[1]));
}

/*---------------------------------------------------------------------------*/

void vr_input_init(void)
{
    ready  = 0;
    failed = 0;
}

void vr_input_free(void)
{
    if (act_set != XR_NULL_HANDLE)
        xrDestroyActionSet(act_set);

    act_set = XR_NULL_HANDLE;
    ready   = 0;
    failed  = 0;
}

void vr_input_poll(void)
{
    XrActiveActionSet active;
    XrActionsSyncInfo sync;

    if (failed || !hmd_stat() || !hmd_xr_time())
        return;

    if (!ready)
    {
        if (!(ready = init_actions()))
        {
            log_printf("VR input: giving up on the controllers\n");
            failed = 1;
            return;
        }
    }

    memset(&active, 0, sizeof (active));
    active.actionSet     = act_set;
    active.subactionPath = XR_NULL_PATH;

    memset(&sync, 0, sizeof (sync));
    sync.type                  = XR_TYPE_ACTIONS_SYNC_INFO;
    sync.countActiveActionSets = 1;
    sync.activeActionSets      = &active;

    /* Not being focused is reported as success with everything inactive,
     * so there is nothing to special-case here. */

    if (XR_FAILED(xrSyncActions(hmd_xr_session(), &sync)))
        return;

    poll_sticks();
    poll_buttons();
    poll_pointer();
    poll_wrist();
}

/*---------------------------------------------------------------------------*/
