/* Generated by Claude Code 2.1.263 (claude-opus-5[1m]) */

#include "vr_input.h"

/*---------------------------------------------------------------------------*/

void vr_input_init(void) { }
void vr_input_free(void) { }
int  vr_input_poll(void) { return 1; }

/*---------------------------------------------------------------------------*/
