/* Generated by Claude Code 2.1.263 (claude-opus-5[1m]) */

package org.neverball;

import org.libsdl.app.SDLActivity;

/**
 * Neverball's Android entry point.
 *
 * SDL supplies the Android lifecycle, JNI environment and audio; OpenXR owns
 * the display. SDL's own window is created but never presented to.
 */
public class NeverballActivity extends SDLActivity
{
    @Override
    protected String[] getLibraries()
    {
        /* The last entry is also the library SDL looks up SDL_main in. */

        return new String[] { "SDL2", "neverball" };
    }
}
